import type {
    ChickenFarmBalance,
    CombatStats,
    DifficultyConfig,
    DifficultyId,
    EnemyId,
} from './balanceTypes';
import { BUILDING_TEMPLATES } from './buildingTemplates';

export type {
    BuildingTemplateConfig,
    ChickenFarmBalance,
    CombatStats,
    CoreBuildingId,
    DefenseBuildingConfig,
    DefenseBuildingId,
    DefenderConfig,
    DefenderId,
    DifficultyConfig,
    DifficultyId,
    EconomyBalance,
    EconomyBuildingId,
    EnemyConfig,
    EnemyId,
    IncomeBuildingConfig,
    IncomeBuildingId,
    MarketBuildingId,
    MvpBuildingId,
    PathingBalance,
    ProductionBuildingId,
    ResearchBuildingId,
    ScoreBalance,
    SessionBalance,
    ShopItemConfig,
    ShopItemId,
    SourceTrace,
    WaveBalance,
    WaveEvent,
    WolfFocusRule,
    WolfOrderRefreshRule,
    WolfTargetClass,
    WorldRect,
} from './balanceTypes';

const WOLF_MELEE_ATTACK_RANGE_PX = 34;
const WOLF_AUTO_ACQUIRE_RANGE_PX = 176;
const WOLF_RANGE_LEASH_PX = 16;
const WOLF_WINDUP_SEC = 0.18;
const BOSS_AUTO_ACQUIRE_RANGE_PX = 208;

export const CHICKEN_FARM_BALANCE: ChickenFarmBalance = {
    buildingTemplates: BUILDING_TEMPLATES,
    defenders: {
        big_dog: {
            armor: 4,
            attackCooldownSec: 1,
            damage: 45,
            hp: 650,
            id: 'big_dog',
            role: 'elite_defender',
            source: {
                rawcode: 'n00E',
            },
            speedPxPerSec: 330,
        },
        dog: {
            armor: 2,
            attackCooldownSec: 0.8,
            damage: 18,
            hp: 220,
            id: 'dog',
            role: 'fast_defender',
            source: {
                rawcode: 'n002',
            },
            speedPxPerSec: 290,
        },
        farmer: {
            armor: 0,
            attackCooldownSec: 0.9,
            damage: 10,
            hp: 100,
            id: 'farmer',
            role: 'builder_hero',
            source: {
                rawcode: 'H000',
            },
            speedPxPerSec: 240,
        },
    },
    difficulties: {
        crazy: {
            enemyDamageMultiplier: 1.25,
            enemyHpMultiplier: 1.4,
            id: 'crazy',
            label: 'Crazy',
            startingCoinsBonus: -10,
        },
        easy: {
            enemyDamageMultiplier: 0.85,
            enemyHpMultiplier: 0.85,
            id: 'easy',
            label: 'Easy',
            startingCoinsBonus: 20,
        },
        hard: {
            enemyDamageMultiplier: 1.15,
            enemyHpMultiplier: 1.2,
            id: 'hard',
            label: 'Hard',
            startingCoinsBonus: 0,
        },
        normal: {
            enemyDamageMultiplier: 1,
            enemyHpMultiplier: 1,
            id: 'normal',
            label: 'Normal',
            startingCoinsBonus: 0,
        },
    },
    economy: {
        easyBonusCoins: 20,
        eggUnitValueCoins: 12,
        exchangeEnabled: false,
        reviveResourceLossPct: 25,
        startingCoins: 120,
    },
    enemies: {
        archimonde: {
            armor: 4,
            attackCooldownSec: 1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 46,
            hp: 700,
            id: 'archimonde',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 160,
            source: {
                notes: ['Direct late boss spawn in static JASS analysis.'],
                rawcode: 'H01N',
            },
            speedPxPerSec: 330,
            tags: ['boss', 'final'],
            windupSec: WOLF_WINDUP_SEC,
        },
        blood_wolf: {
            armor: 1,
            attackCooldownSec: 1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 14,
            hp: 130,
            id: 'blood_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 40,
            source: {
                rawcode: 'H012',
            },
            speedPxPerSec: 330,
            tags: ['boss'],
            windupSec: WOLF_WINDUP_SEC,
        },
        doom_guard: {
            armor: 4,
            attackCooldownSec: 1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 40,
            hp: 600,
            id: 'doom_guard',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 140,
            source: {
                rawcode: 'H01B',
            },
            speedPxPerSec: 330,
            tags: ['boss'],
            windupSec: WOLF_WINDUP_SEC,
        },
        frost_wolf: {
            armor: 1,
            attackCooldownSec: 1.1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: WOLF_AUTO_ACQUIRE_RANGE_PX,
            damage: 12,
            hp: 140,
            id: 'frost_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 15,
            source: {
                rawcode: 'n008',
            },
            speedPxPerSec: 330,
            tags: ['ordinary'],
            windupSec: WOLF_WINDUP_SEC,
        },
        giant_wolf: {
            armor: 1,
            attackCooldownSec: 1.15,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: WOLF_AUTO_ACQUIRE_RANGE_PX,
            damage: 16,
            hp: 175,
            id: 'giant_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 20,
            source: {
                rawcode: 'n009',
            },
            speedPxPerSec: 330,
            tags: ['ordinary'],
            windupSec: WOLF_WINDUP_SEC,
        },
        hell_hound: {
            armor: 3,
            attackCooldownSec: 0.9,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 32,
            hp: 360,
            id: 'hell_hound',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 100,
            source: {
                rawcode: 'H013',
            },
            speedPxPerSec: 330,
            tags: ['boss'],
            windupSec: WOLF_WINDUP_SEC,
        },
        nether_dragon: {
            armor: 5,
            attackCooldownSec: 1.05,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 48,
            hp: 900,
            id: 'nether_dragon',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 200,
            source: {
                notes: [
                    'Likely spawned after death/transform event; verify with actual play.',
                ],
                rawcode: 'H01O',
            },
            speedPxPerSec: 330,
            tags: ['boss', 'final', 'requires_play_observation'],
            windupSec: WOLF_WINDUP_SEC,
        },
        timber_wolf: {
            armor: 0,
            attackCooldownSec: 1.1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: WOLF_AUTO_ACQUIRE_RANGE_PX,
            damage: 8,
            hp: 100,
            id: 'timber_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 10,
            source: {
                rawcode: 'n007',
            },
            speedPxPerSec: 330,
            tags: ['ordinary'],
            windupSec: WOLF_WINDUP_SEC,
        },
        wild_wolf: {
            armor: 2,
            attackCooldownSec: 0.95,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 22,
            hp: 220,
            id: 'wild_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 70,
            source: {
                rawcode: 'H00X',
            },
            speedPxPerSec: 330,
            tags: ['boss', 'elite'],
            windupSec: WOLF_WINDUP_SEC,
        },
    },
    incomeBuildings: {
        coop_basic: {
            eggUnitsPerTick: 1,
            hp: 120,
            id: 'coop_basic',
            incomeIntervalSec: 30,
            sellValueCoins: 36,
            source: {
                rawcode: 'h00A',
            },
            upgradeCostCoins: 80,
            upgradeTo: 'coop_mid',
        },
        coop_high: {
            eggUnitsPerTick: 3,
            hp: 180,
            id: 'coop_high',
            incomeIntervalSec: 30,
            sellValueCoins: 132,
            source: {
                rawcode: 'h00W',
            },
        },
        coop_mid: {
            eggUnitsPerTick: 2,
            hp: 150,
            id: 'coop_mid',
            incomeIntervalSec: 30,
            sellValueCoins: 72,
            source: {
                rawcode: 'h00J',
            },
            upgradeCostCoins: 140,
            upgradeTo: 'coop_high',
        },
    },
    defenseBuildings: {
        barrier_magic: {
            armor: 8,
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 46,
            hp: 650,
            id: 'barrier_magic',
            requires: 'workshop',
            source: {
                notes: ['Original chain h00K -> h00Y -> h014.'],
                rawcode: 'h00Y',
            },
            targetableByWolves: true,
            upgradeCostCoins: 64,
            upgradeTo: 'plasma_wall',
        },
        fence_bronze: {
            armor: 2,
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 22,
            hp: 300,
            id: 'fence_bronze',
            source: {
                rawcode: 'h00L',
            },
            targetableByWolves: true,
            upgradeCostCoins: 26,
            upgradeTo: 'wall_stone',
        },
        fence_wood: {
            armor: 1,
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 8,
            hp: 200,
            id: 'fence_wood',
            source: {
                rawcode: 'h003',
            },
            targetableByWolves: true,
            upgradeCostCoins: 18,
            upgradeTo: 'fence_bronze',
        },
        gate_wood: {
            armor: 7,
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 18,
            hp: 300,
            id: 'gate_wood',
            requires: 'family_temple',
            source: {
                notes: ['High-confidence h006 closed gate candidate.'],
                rawcode: 'h006',
            },
            targetableByWolves: true,
        },
        plasma_wall: {
            armor: 20,
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 110,
            hp: 1600,
            id: 'plasma_wall',
            requires: 'family_temple',
            source: {
                notes: [
                    'High-confidence final wall h01G; medium h014/h01D intermediates skipped for MVP.',
                ],
                rawcode: 'h01G',
            },
            targetableByWolves: true,
        },
        tower_arcane_grand: {
            armor: 13,
            attack: {
                cooldownSec: 0.7,
                damage: 76,
                rangePx: 360,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 230,
            hp: 1000,
            id: 'tower_arcane_grand',
            requires: 'family_temple',
            source: {
                rawcode: 'h01K',
            },
            targetableByWolves: true,
        },
        tower_arcane_large: {
            armor: 9,
            attack: {
                cooldownSec: 0.7,
                damage: 54,
                rangePx: 330,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 160,
            hp: 800,
            id: 'tower_arcane_large',
            requires: 'family_temple',
            source: {
                rawcode: 'h017',
            },
            targetableByWolves: true,
            upgradeCostCoins: 120,
            upgradeTo: 'tower_arcane_grand',
        },
        tower_arcane_medium: {
            armor: 8,
            attack: {
                cooldownSec: 0.7,
                damage: 38,
                rangePx: 300,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 100,
            hp: 650,
            id: 'tower_arcane_medium',
            requires: 'workshop',
            source: {
                rawcode: 'h008',
            },
            targetableByWolves: true,
            upgradeCostCoins: 80,
            upgradeTo: 'tower_arcane_large',
        },
        tower_arcane_small: {
            armor: 7,
            attack: {
                cooldownSec: 0.7,
                damage: 26,
                rangePx: 270,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 76,
            hp: 400,
            id: 'tower_arcane_small',
            requires: 'coop_basic',
            source: {
                notes: ['Branch from h00D scout tower.'],
                rawcode: 'h016',
            },
            targetableByWolves: true,
            upgradeCostCoins: 58,
            upgradeTo: 'tower_arcane_medium',
        },
        tower_guard_black: {
            armor: 12,
            attack: {
                cooldownSec: 0.9,
                damage: 64,
                rangePx: 345,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 220,
            hp: 900,
            id: 'tower_guard_black',
            requires: 'family_temple',
            source: {
                rawcode: 'h01J',
            },
            targetableByWolves: true,
        },
        tower_guard_large: {
            armor: 8,
            attack: {
                cooldownSec: 0.8,
                damage: 40,
                rangePx: 285,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 76,
            hp: 550,
            id: 'tower_guard_large',
            requires: 'workshop',
            source: {
                rawcode: 'h00Z',
            },
            targetableByWolves: true,
            upgradeCostCoins: 90,
            upgradeTo: 'tower_guard_grand',
        },
        tower_guard_grand: {
            armor: 9,
            attack: {
                cooldownSec: 0.9,
                damage: 46,
                rangePx: 315,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 132,
            hp: 750,
            id: 'tower_guard_grand',
            requires: 'family_temple',
            source: {
                rawcode: 'h00R',
            },
            targetableByWolves: true,
            upgradeCostCoins: 118,
            upgradeTo: 'tower_guard_black',
        },
        tower_guard_medium: {
            armor: 7,
            attack: {
                cooldownSec: 0.85,
                damage: 34,
                rangePx: 255,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 56,
            hp: 400,
            id: 'tower_guard_medium',
            requires: 'coop_basic',
            source: {
                rawcode: 'h00Q',
            },
            targetableByWolves: true,
            upgradeCostCoins: 44,
            upgradeTo: 'tower_guard_large',
        },
        tower_guard_small: {
            armor: 6,
            attack: {
                cooldownSec: 0.9,
                damage: 22,
                rangePx: 225,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 44,
            hp: 300,
            id: 'tower_guard_small',
            requires: 'coop_basic',
            source: {
                notes: ['Branch from h00D scout tower.'],
                rawcode: 'h007',
            },
            targetableByWolves: true,
            upgradeCostCoins: 34,
            upgradeTo: 'tower_guard_medium',
        },
        tower_scout: {
            armor: 5,
            attack: {
                cooldownSec: 1.05,
                damage: 14,
                rangePx: 195,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 32,
            hp: 275,
            id: 'tower_scout',
            source: {
                rawcode: 'h00D',
            },
            targetableByWolves: true,
            upgradeCostCoins: 34,
            upgradeTo: 'tower_guard_small',
        },
        wall_stone: {
            armor: 5,
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 34,
            hp: 450,
            id: 'wall_stone',
            requires: 'coop_basic',
            source: {
                rawcode: 'h00K',
            },
            targetableByWolves: true,
            upgradeCostCoins: 40,
            upgradeTo: 'barrier_magic',
        },
        well_basic: {
            armor: 0,
            aura: {
                amountPerSec: 2,
                kind: 'heal',
                rangePx: 96,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costCoins: 30,
            hp: 100,
            id: 'well_basic',
            source: {
                rawcode: 'h00M',
            },
            targetableByWolves: true,
        },
    },
    pathing: {
        baseBlockedRatioTarget: 0.04,
        blockerAttackAcquire: {
            blockedToBlockerDelaySec: 0.8,
            maxRepathAttemptsBeforeBlocker: 2,
            searchRadiusPx: 96,
        },
        cellSize: 32,
        centralHubBuildable: false,
        dynamicBlockersEnabled: true,
        farmAreaBuildable: true,
        pathSmoothingEnabled: true,
        repath: {
            blockedGraceSec: 0.25,
            intervalSec: 0.5,
            targetMoveThresholdPx: 64,
        },
        unitClearanceCells: {
            builder: 1,
            defender: 1,
            wolf: 2,
        },
        wolfAi: {
            acquireIntervalSec: 0.35,
            attackMoveEnabled: true,
            jassOrderModel: {
                blockerTargeting: 'path_failure_only',
                globalAttackRect: {
                    maxX: 7008,
                    maxY: 2848,
                    minX: -3168,
                    minY: -7424,
                },
                optionalFocusRules: [
                    {
                        enabledByDefault: false,
                        jassFlowType: 'boss_or_special_focus_position',
                        jassFunction: 'llIIIi -> lillli',
                        radiusPx: 6000,
                        sourceLines: '3505-3507',
                        translation:
                            'Optional boss/special aggro pulse that pulls nearby wolves toward an attacked special unit position.',
                    },
                    {
                        enabledByDefault: false,
                        jassFlowType: 'low_hp_defender_taunt',
                        jassFunction: 'lIlIIiI -> lIlIIII',
                        radiusPx: 800,
                        sourceLines: '9419-9430',
                        translation:
                            'Optional big-dog/defender taunt when the defender is attacked at very low HP.',
                    },
                    {
                        enabledByDefault: false,
                        jassFlowType: 'manual_tank_focus',
                        jassFunction: 'llIliI -> llIlII',
                        radiusPx: 1200,
                        sourceLines: '1341-1343',
                        translation:
                            'Optional marked tank focus flow. Keep disabled until player command/taunt systems exist.',
                    },
                ],
                periodicAttackRefresh: {
                    enabled: true,
                    intervalSec: 60,
                    jassFlowType: 'periodic_global_attack_refresh',
                    jassFunction: 'IliiIlI -> IliiIiI',
                    order: 'attack_move_random_point_in_global_rect',
                    sourceLines: '5726-5728',
                    unitScope: 'all_wolves',
                },
                spawnEntryAttackRefresh: {
                    enabled: true,
                    jassFlowType: 'spawn_rect_enter_attack',
                    jassFunction: 'IliiIII',
                    order: 'attack_move_random_point_in_global_rect',
                    sourceLines: '5720-5722',
                    unitScope: 'trigger_wolf',
                },
            },
            primaryTargetClasses: [
                'income_building',
                'livestock',
                'core_building',
                'builder_hero',
            ],
            proximityTargetClasses: [
                'defender',
                'income_building',
                'builder_hero',
                'defense_building',
            ],
        },
        wolfBlockedByPlayerFence: true,
    },
    score: {
        survivalEvery10Sec: 5,
    },
    session: {
        finalPressureSec: 780,
        firstWaveSec: 70,
        incomeIntervalSec: 30,
        targetSessionSec: 840,
        waveCheckIntervalSec: 20,
    },
    shopItems: {
        big_dog: {
            costCoins: 180,
            id: 'big_dog',
            kind: 'defender',
            produces: 'big_dog',
        },
        coop_basic: {
            costCoins: 60,
            id: 'coop_basic',
            kind: 'income_building',
            produces: 'coop_basic',
        },
        coop_high: {
            costCoins: 220,
            id: 'coop_high',
            kind: 'income_building',
            produces: 'coop_high',
        },
        coop_mid: {
            costCoins: 120,
            id: 'coop_mid',
            kind: 'income_building',
            produces: 'coop_mid',
        },
        dog: {
            costCoins: 45,
            id: 'dog',
            kind: 'defender',
            produces: 'dog',
        },
    },
    waves: {
        replenishBatchSize: 2,
        replenishMinAliveBase: 2,
        replenishMinAliveMax: 6,
        timeline: [
            {
                atSec: 70,
                count: 4,
                enemyId: 'timber_wolf',
                group: 'ordinary',
            },
            {
                atSec: 120,
                count: 6,
                enemyId: 'timber_wolf',
                group: 'ordinary',
            },
            {
                atSec: 180,
                count: 5,
                enemyId: 'frost_wolf',
                group: 'ordinary',
            },
            {
                atSec: 240,
                count: 4,
                enemyId: 'giant_wolf',
                group: 'ordinary',
            },
            {
                atSec: 300,
                count: 1,
                enemyId: 'blood_wolf',
                group: 'boss',
            },
            {
                atSec: 420,
                count: 1,
                enemyId: 'wild_wolf',
                group: 'boss',
            },
            {
                atSec: 540,
                count: 1,
                enemyId: 'hell_hound',
                group: 'boss',
            },
            {
                atSec: 660,
                count: 1,
                enemyId: 'doom_guard',
                group: 'boss',
            },
            {
                atSec: 780,
                count: 1,
                enemyId: 'archimonde',
                group: 'final',
            },
            {
                atSec: null,
                condition:
                    'Spawn after archimonde death only if actual play confirms the transform.',
                count: 1,
                enemyId: 'nether_dragon',
                group: 'final',
            },
        ],
    },
};

export const DEFAULT_DIFFICULTY: DifficultyId = 'normal';

export function getDifficultyConfig(
    difficulty: DifficultyId = DEFAULT_DIFFICULTY,
): DifficultyConfig {
    return CHICKEN_FARM_BALANCE.difficulties[difficulty];
}

export function getStartingCoins(
    difficulty: DifficultyId = DEFAULT_DIFFICULTY,
): number {
    const config = getDifficultyConfig(difficulty);
    return CHICKEN_FARM_BALANCE.economy.startingCoins + config.startingCoinsBonus;
}

export function getScaledEnemyStats(
    enemyId: EnemyId,
    difficulty: DifficultyId = DEFAULT_DIFFICULTY,
): CombatStats {
    const enemy = CHICKEN_FARM_BALANCE.enemies[enemyId];
    const config = getDifficultyConfig(difficulty);

    return {
        armor: enemy.armor,
        attackCooldownSec: enemy.attackCooldownSec,
        attackRangePx: enemy.attackRangePx,
        acquireRangePx: enemy.acquireRangePx,
        damage: Math.round(enemy.damage * config.enemyDamageMultiplier),
        hp: Math.round(enemy.hp * config.enemyHpMultiplier),
        rangeLeashPx: enemy.rangeLeashPx,
        speedPxPerSec: enemy.speedPxPerSec,
        windupSec: enemy.windupSec,
    };
}
