import type {
    ChickenFarmBalance,
    CombatStats,
    DifficultyConfig,
    DifficultyId,
    EnemyId,
    WaveBossMilestone,
    WaveTierDelta,
} from './balanceTypes';
import { BUILDING_TEMPLATES } from './buildingTemplates';

export type {
    BuildingTemplateConfig,
    ChickenFarmBalance,
    CombatStats,
    CoreBuildingId,
    DefenseBuildingConfig,
    DefenseBuildingId,
    DefenderConfig,
    DefenderId,
    DifficultyConfig,
    DifficultyId,
    EconomyBalance,
    EconomyBuildingId,
    EnemyConfig,
    EnemyId,
    IncomeBuildingConfig,
    IncomeBuildingId,
    LumberMillId,
    LumberMillIncomeConfig,
    MarketBuildingId,
    MvpBuildingId,
    OrdinaryWavePhase,
    PathingBalance,
    ProductionBuildingId,
    ResearchBuildingId,
    ScoreBalance,
    SessionBalance,
    ShopItemConfig,
    ShopItemId,
    SourceTrace,
    WaveBalance,
    WaveBossMilestone,
    WaveTierDelta,
    WolfFocusRule,
    WolfOrderRefreshRule,
    WolfTargetClass,
    WorldRect,
} from './balanceTypes';

const WOLF_MELEE_ATTACK_RANGE_PX = 96;
const WOLF_AUTO_ACQUIRE_RANGE_PX = 176;
const WOLF_RANGE_LEASH_PX = 16;
const WOLF_WINDUP_SEC = 0.18;
const BOSS_AUTO_ACQUIRE_RANGE_PX = 208;

function ordinaryWolf(config: {
    readonly armor: number;
    readonly attackCooldownSec: number;
    readonly damage: number;
    readonly hp: number;
    readonly id: EnemyId;
    readonly rawcode: string;
    readonly score: number;
    readonly speedPxPerSec: number;
}) {
    return {
        ...config,
        attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
        acquireRangePx: WOLF_AUTO_ACQUIRE_RANGE_PX,
        rangeLeashPx: WOLF_RANGE_LEASH_PX,
        source: {
            notes: [
                'W3X dice damage is converted to rounded fixed average damage for the web combat model.',
            ],
            rawcode: config.rawcode,
        },
        tags: ['ordinary'] as const,
        windupSec: WOLF_WINDUP_SEC,
    };
}

export const CHICKEN_FARM_BALANCE: ChickenFarmBalance = {
    buildingTemplates: BUILDING_TEMPLATES,
    defenders: {
        big_dog: {
            armor: 4,
            attackCooldownSec: 1,
            damage: 45,
            hp: 650,
            id: 'big_dog',
            role: 'elite_defender',
            source: {
                rawcode: 'n00E',
            },
            speedPxPerSec: 330,
        },
        dog: {
            armor: 2,
            attackCooldownSec: 0.8,
            damage: 18,
            hp: 220,
            mana: 30,
            manaRegenPerSec: 0.25,
            id: 'dog',
            role: 'fast_defender',
            source: {
                rawcode: 'n002',
            },
            speedPxPerSec: 290,
        },
        farmer: {
            armor: 0,
            attackCooldownSec: 0.9,
            damage: 10,
            hp: 100,
            mana: 60,
            manaRegenPerSec: 0.5,
            id: 'farmer',
            role: 'builder_hero',
            source: {
                rawcode: 'H000',
            },
            speedPxPerSec: 240,
        },
    },
    difficulties: {
        crazy: {
            bossSpecialAbilitiesEnabled: false,
            enemyArmorBonus: 0,
            enemyArmorMultiplier: 1,
            enemyAttackSpeedMultiplier: 1.7,
            enemyDamageMultiplier: 1.7,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 1,
            id: 'crazy',
            label: 'Crazy',
            startingGoldBonus: 0,
        },
        easy: {
            bossSpecialAbilitiesEnabled: false,
            enemyArmorBonus: 0,
            enemyArmorMultiplier: 0.7,
            enemyAttackSpeedMultiplier: 0.7,
            enemyDamageMultiplier: 1,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 0.7,
            id: 'easy',
            label: 'Easy',
            startingGoldBonus: 200,
        },
        hard: {
            bossSpecialAbilitiesEnabled: false,
            enemyArmorBonus: 0,
            enemyArmorMultiplier: 1,
            enemyAttackSpeedMultiplier: 1.4,
            enemyDamageMultiplier: 1,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 1,
            id: 'hard',
            label: 'Hard',
            startingGoldBonus: 0,
        },
        impossible: {
            bossSpecialAbilitiesEnabled: false,
            enemyArmorBonus: 10,
            enemyArmorMultiplier: 1,
            enemyAttackSpeedMultiplier: 2.5,
            enemyDamageMultiplier: 2.5,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 1,
            id: 'impossible',
            label: 'Impossible',
            startingGoldBonus: 0,
        },
        mad: {
            bossSpecialAbilitiesEnabled: false,
            enemyArmorBonus: 5,
            enemyArmorMultiplier: 1,
            enemyAttackSpeedMultiplier: 2,
            enemyDamageMultiplier: 2,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 1,
            id: 'mad',
            label: 'Mad',
            startingGoldBonus: 0,
        },
        normal: {
            bossSpecialAbilitiesEnabled: false,
            enemyArmorBonus: 0,
            enemyArmorMultiplier: 1,
            enemyAttackSpeedMultiplier: 1,
            enemyDamageMultiplier: 1,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 1,
            id: 'normal',
            label: 'Normal',
            startingGoldBonus: 0,
        },
        special: {
            bossSpecialAbilitiesEnabled: false,
            enemyArmorBonus: 0,
            enemyArmorMultiplier: 1,
            enemyAttackSpeedMultiplier: 1.7,
            enemyDamageMultiplier: 1,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 1,
            id: 'special',
            label: 'Special',
            startingGoldBonus: 0,
        },
        unlimited: {
            bossSpecialAbilitiesEnabled: true,
            enemyArmorBonus: 0,
            enemyArmorMultiplier: 1,
            enemyAttackSpeedMultiplier: 1,
            enemyDamageMultiplier: 1,
            enemyHpMultiplier: 1,
            enemyMoveSpeedMultiplier: 1,
            id: 'unlimited',
            label: 'Unlimited',
            startingGoldBonus: 0,
        },
    },
    economy: {
        easyBonusGold: 200,
        eggSellValueGold: 12,
        exchangeEnabled: true,
        marketExchangeGoldCost: 100,
        marketExchangeLumberGain: 70,
        reviveResourceLossPct: 40,
        startingGold: 1500,
        startingLumber: 0,
        startingSupplyCap: 3,
    },
    enemies: {
        archimonde: {
            armor: 4,
            attackCooldownSec: 1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 46,
            hp: 700,
            id: 'archimonde',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 160,
            source: {
                notes: ['Direct late boss spawn in static JASS analysis.'],
                rawcode: 'H01N',
            },
            speedPxPerSec: 330,
            tags: ['boss', 'final'],
            windupSec: WOLF_WINDUP_SEC,
        },
        blood_wolf: {
            armor: 1,
            attackCooldownSec: 1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 14,
            hp: 130,
            id: 'blood_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 40,
            source: {
                rawcode: 'H012',
            },
            speedPxPerSec: 330,
            tags: ['boss'],
            windupSec: WOLF_WINDUP_SEC,
        },
        doom_guard: {
            armor: 4,
            attackCooldownSec: 1,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 40,
            hp: 600,
            id: 'doom_guard',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 140,
            source: {
                rawcode: 'H01B',
            },
            speedPxPerSec: 330,
            tags: ['boss'],
            windupSec: WOLF_WINDUP_SEC,
        },
        frost_wolf: {
            armor: 1,
            attackCooldownSec: 1.35,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: WOLF_AUTO_ACQUIRE_RANGE_PX,
            damage: 19,
            hp: 600,
            id: 'frost_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 15,
            source: {
                rawcode: 'n008',
            },
            speedPxPerSec: 330,
            tags: ['ordinary'],
            windupSec: WOLF_WINDUP_SEC,
        },
        giant_wolf: {
            armor: 1,
            attackCooldownSec: 1.35,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: WOLF_AUTO_ACQUIRE_RANGE_PX,
            damage: 23,
            hp: 700,
            id: 'giant_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 20,
            source: {
                rawcode: 'n009',
            },
            speedPxPerSec: 330,
            tags: ['ordinary'],
            windupSec: WOLF_WINDUP_SEC,
        },
        giant_frost_wolf: ordinaryWolf({
            armor: 2,
            attackCooldownSec: 1.35,
            damage: 26,
            hp: 800,
            id: 'giant_frost_wolf',
            rawcode: 'n00A',
            score: 40,
            speedPxPerSec: 330,
        }),
        dire_wolf: ordinaryWolf({
            armor: 2,
            attackCooldownSec: 1.35,
            damage: 30,
            hp: 700,
            id: 'dire_wolf',
            rawcode: 'n00B',
            score: 50,
            speedPxPerSec: 330,
        }),
        dire_frost_wolf: ordinaryWolf({
            armor: 3,
            attackCooldownSec: 1.35,
            damage: 32,
            hp: 750,
            id: 'dire_frost_wolf',
            rawcode: 'n00C',
            score: 60,
            speedPxPerSec: 330,
        }),
        spirit_wolf: ordinaryWolf({
            armor: 5,
            attackCooldownSec: 1.35,
            damage: 57,
            hp: 1900,
            id: 'spirit_wolf',
            rawcode: 'n00G',
            score: 70,
            speedPxPerSec: 330,
        }),
        dire_wolf_tier_8: ordinaryWolf({
            armor: 5,
            attackCooldownSec: 1.35,
            damage: 64,
            hp: 2200,
            id: 'dire_wolf_tier_8',
            rawcode: 'n00I',
            score: 80,
            speedPxPerSec: 330,
        }),
        shadow_wolf: ordinaryWolf({
            armor: 6,
            attackCooldownSec: 1.35,
            damage: 71,
            hp: 2700,
            id: 'shadow_wolf',
            rawcode: 'n00J',
            score: 90,
            speedPxPerSec: 330,
        }),
        fel_beast: ordinaryWolf({
            armor: 7,
            attackCooldownSec: 1.35,
            damage: 91,
            hp: 700,
            id: 'fel_beast',
            rawcode: 'n00K',
            score: 100,
            speedPxPerSec: 350,
        }),
        fel_stalker: ordinaryWolf({
            armor: 8,
            attackCooldownSec: 1.35,
            damage: 108,
            hp: 6500,
            id: 'fel_stalker',
            rawcode: 'n00L',
            score: 110,
            speedPxPerSec: 350,
        }),
        fel_ravager: ordinaryWolf({
            armor: 9,
            attackCooldownSec: 1.35,
            damage: 125,
            hp: 7500,
            id: 'fel_ravager',
            rawcode: 'n00M',
            score: 120,
            speedPxPerSec: 350,
        }),
        darkguard: ordinaryWolf({
            armor: 10,
            attackCooldownSec: 1.35,
            damage: 147,
            hp: 14000,
            id: 'darkguard',
            rawcode: 'n00U',
            score: 130,
            speedPxPerSec: 330,
        }),
        shupikuta: ordinaryWolf({
            armor: 12,
            attackCooldownSec: 1.35,
            damage: 171,
            hp: 19000,
            id: 'shupikuta',
            rawcode: 'n00V',
            score: 140,
            speedPxPerSec: 330,
        }),
        overlord: ordinaryWolf({
            armor: 14,
            attackCooldownSec: 1.35,
            damage: 187,
            hp: 17500,
            id: 'overlord',
            rawcode: 'n00W',
            score: 150,
            speedPxPerSec: 330,
        }),
        satyr: ordinaryWolf({
            armor: 15,
            attackCooldownSec: 1.35,
            damage: 215,
            hp: 17000,
            id: 'satyr',
            rawcode: 'n013',
            score: 160,
            speedPxPerSec: 330,
        }),
        satyr_soulstealer: ordinaryWolf({
            armor: 18,
            attackCooldownSec: 1.35,
            damage: 248,
            hp: 19000,
            id: 'satyr_soulstealer',
            rawcode: 'n015',
            score: 170,
            speedPxPerSec: 330,
        }),
        satyr_shadowdancer: ordinaryWolf({
            armor: 24,
            attackCooldownSec: 1.35,
            damage: 291,
            hp: 22000,
            id: 'satyr_shadowdancer',
            rawcode: 'n014',
            score: 180,
            speedPxPerSec: 330,
        }),
        hell_hound: {
            armor: 3,
            attackCooldownSec: 0.9,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 32,
            hp: 360,
            id: 'hell_hound',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 100,
            source: {
                rawcode: 'H013',
            },
            speedPxPerSec: 330,
            tags: ['boss'],
            windupSec: WOLF_WINDUP_SEC,
        },
        nether_dragon: {
            armor: 5,
            attackCooldownSec: 1.05,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 48,
            hp: 900,
            id: 'nether_dragon',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 200,
            source: {
                notes: [
                    'Likely spawned after death/transform event; verify with actual play.',
                ],
                rawcode: 'H01O',
            },
            speedPxPerSec: 330,
            tags: ['boss', 'final', 'requires_play_observation'],
            windupSec: WOLF_WINDUP_SEC,
        },
        timber_wolf: {
            armor: 0,
            attackCooldownSec: 1.35,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: WOLF_AUTO_ACQUIRE_RANGE_PX,
            damage: 13,
            hp: 450,
            id: 'timber_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 10,
            source: {
                notes: [
                    'Original n007 damage is base 11 + 1d2, so Phaser fixed damage uses rounded average 13.',
                ],
                rawcode: 'n007',
            },
            speedPxPerSec: 330,
            tags: ['ordinary'],
            windupSec: WOLF_WINDUP_SEC,
        },
        wild_wolf: {
            armor: 2,
            attackCooldownSec: 0.95,
            attackRangePx: WOLF_MELEE_ATTACK_RANGE_PX,
            acquireRangePx: BOSS_AUTO_ACQUIRE_RANGE_PX,
            damage: 22,
            hp: 220,
            id: 'wild_wolf',
            rangeLeashPx: WOLF_RANGE_LEASH_PX,
            score: 70,
            source: {
                rawcode: 'H00X',
            },
            speedPxPerSec: 330,
            tags: ['boss', 'elite'],
            windupSec: WOLF_WINDUP_SEC,
        },
    },
    incomeBuildings: {
        coop_basic: {
            eggUnitsPerTick: 1,
            hp: 120,
            id: 'coop_basic',
            incomeIntervalSec: 30,
            sellValueCoins: 36,
            source: {
                rawcode: 'h00A',
            },
            upgradeCostGold: 80,
            upgradeTo: 'coop_mid',
        },
        coop_high: {
            eggUnitsPerTick: 3,
            hp: 180,
            id: 'coop_high',
            incomeIntervalSec: 30,
            sellValueCoins: 132,
            source: {
                rawcode: 'h00W',
            },
        },
        coop_mid: {
            eggUnitsPerTick: 2,
            hp: 150,
            id: 'coop_mid',
            incomeIntervalSec: 30,
            sellValueCoins: 72,
            source: {
                rawcode: 'h00J',
            },
            upgradeCostGold: 140,
            upgradeTo: 'coop_high',
        },
    },
    lumberMillIncome: {
        lumber_mill: {
            incomeIntervalSec: 30,
            lumberPerTick: 70,
            source: { rawcode: 'h00A' },
            templateId: 'lumber_mill',
        },
        lumber_mill_high: {
            incomeIntervalSec: 30,
            lumberPerTick: 170,
            source: { rawcode: 'h00W' },
            templateId: 'lumber_mill_high',
        },
        lumber_mill_mid: {
            incomeIntervalSec: 30,
            lumberPerTick: 110,
            source: { rawcode: 'h00J' },
            templateId: 'lumber_mill_mid',
        },
    },
    defenseBuildings: {
        barrier_magic: {
            armor: 8,
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 46,
            hp: 650,
            id: 'barrier_magic',
            requires: 'workshop',
            source: {
                notes: ['Original chain h00K -> h00Y -> h014.'],
                rawcode: 'h00Y',
            },
            targetableByWolves: true,
            upgradeCostGold: 64,
            upgradeTo: 'plasma_wall',
        },
        fence_bronze: {
            armor: 2,
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 22,
            hp: 300,
            id: 'fence_bronze',
            source: {
                rawcode: 'h00L',
            },
            targetableByWolves: true,
            upgradeCostGold: 26,
            upgradeTo: 'wall_stone',
        },
        fence_wood: {
            armor: 1,
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 8,
            hp: 200,
            id: 'fence_wood',
            source: {
                rawcode: 'h003',
            },
            targetableByWolves: true,
            upgradeCostGold: 18,
            upgradeTo: 'fence_bronze',
        },
        gate_wood: {
            armor: 7,
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 18,
            hp: 300,
            id: 'gate_wood',
            requires: 'family_temple',
            source: {
                notes: ['High-confidence h006 closed gate candidate.'],
                rawcode: 'h006',
            },
            targetableByWolves: true,
        },
        plasma_wall: {
            armor: 20,
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 110,
            hp: 1600,
            id: 'plasma_wall',
            requires: 'family_temple',
            source: {
                notes: [
                    'High-confidence final wall h01G; medium h014/h01D intermediates skipped for MVP.',
                ],
                rawcode: 'h01G',
            },
            targetableByWolves: true,
        },
        tower_arcane_grand: {
            armor: 13,
            attack: {
                cooldownSec: 0.7,
                damage: 76,
                rangePx: 360,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 230,
            hp: 1000,
            id: 'tower_arcane_grand',
            requires: 'family_temple',
            source: {
                rawcode: 'h01K',
            },
            targetableByWolves: true,
        },
        tower_arcane_large: {
            armor: 9,
            attack: {
                cooldownSec: 0.7,
                damage: 54,
                rangePx: 330,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 160,
            hp: 800,
            id: 'tower_arcane_large',
            requires: 'family_temple',
            source: {
                rawcode: 'h017',
            },
            targetableByWolves: true,
            upgradeCostGold: 120,
            upgradeTo: 'tower_arcane_grand',
        },
        tower_arcane_medium: {
            armor: 8,
            attack: {
                cooldownSec: 0.7,
                damage: 38,
                rangePx: 300,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 100,
            hp: 650,
            id: 'tower_arcane_medium',
            requires: 'workshop',
            source: {
                rawcode: 'h008',
            },
            targetableByWolves: true,
            upgradeCostGold: 80,
            upgradeTo: 'tower_arcane_large',
        },
        tower_arcane_small: {
            armor: 7,
            attack: {
                cooldownSec: 0.7,
                damage: 26,
                rangePx: 270,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 76,
            hp: 400,
            id: 'tower_arcane_small',
            requires: 'coop_basic',
            source: {
                notes: ['Branch from h00D scout tower.'],
                rawcode: 'h016',
            },
            targetableByWolves: true,
            upgradeCostGold: 58,
            upgradeTo: 'tower_arcane_medium',
        },
        tower_guard_black: {
            armor: 12,
            attack: {
                cooldownSec: 0.9,
                damage: 64,
                rangePx: 345,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 220,
            hp: 900,
            id: 'tower_guard_black',
            requires: 'family_temple',
            source: {
                rawcode: 'h01J',
            },
            targetableByWolves: true,
        },
        tower_guard_large: {
            armor: 8,
            attack: {
                cooldownSec: 0.8,
                damage: 40,
                rangePx: 285,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 76,
            hp: 550,
            id: 'tower_guard_large',
            requires: 'workshop',
            source: {
                rawcode: 'h00Z',
            },
            targetableByWolves: true,
            upgradeCostGold: 90,
            upgradeTo: 'tower_guard_grand',
        },
        tower_guard_grand: {
            armor: 9,
            attack: {
                cooldownSec: 0.9,
                damage: 46,
                rangePx: 315,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 132,
            hp: 750,
            id: 'tower_guard_grand',
            requires: 'family_temple',
            source: {
                rawcode: 'h00R',
            },
            targetableByWolves: true,
            upgradeCostGold: 118,
            upgradeTo: 'tower_guard_black',
        },
        tower_guard_medium: {
            armor: 7,
            attack: {
                cooldownSec: 0.85,
                damage: 34,
                rangePx: 255,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 56,
            hp: 400,
            id: 'tower_guard_medium',
            requires: 'coop_basic',
            source: {
                rawcode: 'h00Q',
            },
            targetableByWolves: true,
            upgradeCostGold: 44,
            upgradeTo: 'tower_guard_large',
        },
        tower_guard_small: {
            armor: 6,
            attack: {
                cooldownSec: 0.9,
                damage: 22,
                rangePx: 225,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 44,
            hp: 300,
            id: 'tower_guard_small',
            requires: 'coop_basic',
            source: {
                notes: ['Branch from h00D scout tower.'],
                rawcode: 'h007',
            },
            targetableByWolves: true,
            upgradeCostGold: 34,
            upgradeTo: 'tower_guard_medium',
        },
        tower_scout: {
            armor: 5,
            attack: {
                cooldownSec: 1.05,
                damage: 23,
                // Feel-test candidates: 384px barely covers diagonal fence,
                // 448px reaches a tower-gap-fence line with margin,
                // 512px covers tighter turns, 650px is the original W3X h00D range.
                rangePx: 384,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 32,
            hp: 275,
            id: 'tower_scout',
            source: {
                notes: [
                    'Original h00D attack range is 650 War3 world units. Phaser runtime uses 384px; test candidates are 384/448/512/650.',
                ],
                rawcode: 'h00D',
            },
            targetableByWolves: true,
            upgradeCostGold: 34,
            upgradeTo: 'tower_guard_small',
        },
        wall_stone: {
            armor: 5,
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 34,
            hp: 450,
            id: 'wall_stone',
            requires: 'coop_basic',
            source: {
                rawcode: 'h00K',
            },
            targetableByWolves: true,
            upgradeCostGold: 40,
            upgradeTo: 'barrier_magic',
        },
        well_basic: {
            armor: 0,
            aura: {
                amountPerSec: 2,
                kind: 'heal',
                rangePx: 96,
            },
            blocksPath: true,
            buildTimeSec: 0,
            costGold: 30,
            hp: 100,
            id: 'well_basic',
            source: {
                rawcode: 'h00M',
            },
            targetableByWolves: true,
        },
    },
    pathing: {
        baseBlockedRatioTarget: 0.04,
        blockerAttackAcquire: {
            blockedToBlockerDelaySec: 0.8,
            maxRepathAttemptsBeforeBlocker: 2,
            searchRadiusPx: 96,
        },
        cellSize: 32,
        centralHubBuildable: false,
        dynamicBlockersEnabled: true,
        farmAreaBuildable: true,
        pathSmoothingEnabled: true,
        repath: {
            blockedGraceSec: 0.25,
            intervalSec: 0.5,
            targetMoveThresholdPx: 64,
        },
        unitClearanceCells: {
            builder: 1,
            defender: 1,
            wolf: 2,
        },
        wolfAi: {
            acquireIntervalSec: 0.35,
            aggroAssist: {
                enabled: true,
                includeBlockerAttackers: true,
                includeFarmAttackers: false,
                lockSec: 0.7,
                maxAssistWolvesPerHit: 3,
                radiusPx: 384,
            },
            attackMoveEnabled: true,
            attackMoveRefresh: {
                localRectPaddingPx: 448,
                stuckSec: 3.5,
                targetReachedDistancePx: 64,
            },
            postObjectiveCleanup: {
                enabled: false,
                targetFences: true,
            },
            jassOrderModel: {
                blockerTargeting: 'path_failure_only',
                globalAttackRect: {
                    maxX: 7008,
                    maxY: 2848,
                    minX: -3168,
                    minY: -7424,
                },
                optionalFocusRules: [
                    {
                        enabledByDefault: false,
                        jassFlowType: 'boss_or_special_focus_position',
                        jassFunction: 'llIIIi -> lillli',
                        radiusPx: 6000,
                        sourceLines: '3505-3507',
                        translation:
                            'Optional boss/special aggro pulse that pulls nearby wolves toward an attacked special unit position.',
                    },
                    {
                        enabledByDefault: false,
                        jassFlowType: 'low_hp_defender_taunt',
                        jassFunction: 'lIlIIiI -> lIlIIII',
                        radiusPx: 800,
                        sourceLines: '9419-9430',
                        translation:
                            'Optional big-dog/defender taunt when the defender is attacked at very low HP.',
                    },
                    {
                        enabledByDefault: false,
                        jassFlowType: 'manual_tank_focus',
                        jassFunction: 'llIliI -> llIlII',
                        radiusPx: 1200,
                        sourceLines: '1341-1343',
                        translation:
                            'Optional marked tank focus flow. Keep disabled until player command/taunt systems exist.',
                    },
                ],
                periodicAttackRefresh: {
                    enabled: true,
                    intervalSec: 60,
                    jassFlowType: 'periodic_global_attack_refresh',
                    jassFunction: 'IliiIlI -> IliiIiI',
                    order: 'attack_move_random_point_in_global_rect',
                    sourceLines: '5726-5728',
                    unitScope: 'all_wolves',
                },
                spawnEntryAttackRefresh: {
                    enabled: true,
                    jassFlowType: 'spawn_rect_enter_attack',
                    jassFunction: 'IliiIII',
                    order: 'attack_move_random_point_in_global_rect',
                    sourceLines: '5720-5722',
                    unitScope: 'trigger_wolf',
                },
            },
            primaryTargetClasses: [
                'income_building',
                'livestock',
                'core_building',
                'builder_hero',
            ],
            proximityTargetClasses: [
                'defender',
                'income_building',
                'builder_hero',
                'defense_building',
            ],
        },
        wolfBlockedByPlayerFence: true,
    },
    score: {
        survivalEvery10Sec: 5,
    },
    session: {
        finalPressureSec: 3000,
        firstWaveSec: 120,
        incomeIntervalSec: 30,
        targetSessionSec: 3000,
        waveCheckIntervalSec: 20,
    },
    shopItems: {
        big_dog: {
            costGold: 180,
            id: 'big_dog',
            kind: 'defender',
            produces: 'big_dog',
        },
        coop_basic: {
            costGold: 60,
            id: 'coop_basic',
            kind: 'income_building',
            produces: 'coop_basic',
        },
        coop_high: {
            costGold: 220,
            id: 'coop_high',
            kind: 'income_building',
            produces: 'coop_high',
        },
        coop_mid: {
            costGold: 120,
            id: 'coop_mid',
            kind: 'income_building',
            produces: 'coop_mid',
        },
        dog: {
            costGold: 45,
            id: 'dog',
            kind: 'defender',
            produces: 'dog',
        },
    },
    waves: {
        // SP-10 owns boss spawning and rewards. These are source milestones only.
        bossMilestonesForSp10: [
            { atSec: 600, bossRawcode: 'H012', note: 'Blood Wolf' },
            { atSec: 1500, bossRawcode: 'H00X', note: 'Wild Wolf' },
            { atSec: 2200, bossRawcode: 'H013', note: 'Hell Hound' },
            { atSec: 2600, bossRawcode: 'H01B', note: 'Doom Guard' },
            { atSec: 3000, bossRawcode: 'H01N', note: 'Archimonde' },
        ] satisfies readonly WaveBossMilestone[],
        ordinaryPhases: [
            { activeTiers: [1, 2, 3, 4, 5, 6], atSec: 120, phaseEntryTargetDeltas: [], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [3, 4, 5, 6, 7], atSec: 600, phaseEntryTargetDeltas: [{ amount: 7, tier: 3 }, { amount: 3, tier: 4 }, { amount: 2, tier: 5 }, { amount: 1, tier: 6 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [4, 5, 6, 7, 8, 9], atSec: 1100, phaseEntryTargetDeltas: [{ amount: 5, tier: 4 }, { amount: 3, tier: 5 }, { amount: 2, tier: 6 }, { amount: 1, tier: 7 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [7, 8, 9], atSec: 1500, phaseEntryTargetDeltas: [{ amount: 4, tier: 7 }, { amount: 3, tier: 8 }, { amount: 2, tier: 9 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [8, 9, 10, 11, 12], atSec: 2000, phaseEntryTargetDeltas: [{ amount: 7, tier: 8 }, { amount: 5, tier: 9 }, { amount: 4, tier: 10 }, { amount: 3, tier: 11 }, { amount: 2, tier: 12 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [10, 11, 12], atSec: 2200, phaseEntryTargetDeltas: [{ amount: 7, tier: 10 }, { amount: 4, tier: 11 }, { amount: 3, tier: 12 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [11, 12, 13, 14, 15], atSec: 2400, phaseEntryTargetDeltas: [{ amount: 7, tier: 11 }, { amount: 6, tier: 12 }, { amount: 5, tier: 13 }, { amount: 4, tier: 14 }, { amount: 3, tier: 15 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [13, 14, 15], atSec: 2600, phaseEntryTargetDeltas: [{ amount: 7, tier: 13 }, { amount: 4, tier: 14 }, { amount: 3, tier: 15 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 35 },
            { activeTiers: [14, 15, 16, 17, 18], atSec: 2800, phaseEntryTargetDeltas: [{ amount: 9, tier: 14 }, { amount: 8, tier: 15 }, { amount: 7, tier: 16 }, { amount: 5, tier: 17 }, { amount: 4, tier: 18 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 22 },
            { activeTiers: [16, 17, 18], atSec: 3000, phaseEntryTargetDeltas: [{ amount: 9, tier: 16 }, { amount: 7, tier: 17 }, { amount: 6, tier: 18 }], periodicTargetDeltas: null, replenishIntervalSec: 0.2, targetIncrementIntervalSec: 22 },
        ] satisfies readonly {
            readonly activeTiers: readonly number[];
            readonly atSec: number;
            readonly phaseEntryTargetDeltas: readonly WaveTierDelta[];
            readonly periodicTargetDeltas: null;
            readonly replenishIntervalSec: number;
            readonly targetIncrementIntervalSec: number;
        }[],
        replenishBatchSize: 2,
    },
};

export const DEFAULT_DIFFICULTY: DifficultyId = 'normal';

export function getDifficultyConfig(
    difficulty: DifficultyId = DEFAULT_DIFFICULTY,
): DifficultyConfig {
    return CHICKEN_FARM_BALANCE.difficulties[difficulty];
}

export function getStartingGold(
    difficulty: DifficultyId = DEFAULT_DIFFICULTY,
): number {
    const config = getDifficultyConfig(difficulty);
    return CHICKEN_FARM_BALANCE.economy.startingGold + config.startingGoldBonus;
}

export function getScaledEnemyStats(
    enemyId: EnemyId,
    difficulty: DifficultyId = DEFAULT_DIFFICULTY,
): CombatStats {
    const enemy = CHICKEN_FARM_BALANCE.enemies[enemyId];
    const config = getDifficultyConfig(difficulty);

    return {
        armor: Math.round(
            enemy.armor * config.enemyArmorMultiplier + config.enemyArmorBonus,
        ),
        attackCooldownSec:
            enemy.attackCooldownSec / config.enemyAttackSpeedMultiplier,
        attackRangePx: enemy.attackRangePx,
        acquireRangePx: enemy.acquireRangePx,
        damage: Math.round(enemy.damage * config.enemyDamageMultiplier),
        hp: Math.round(enemy.hp * config.enemyHpMultiplier),
        rangeLeashPx: enemy.rangeLeashPx,
        speedPxPerSec: Math.round(
            enemy.speedPxPerSec * config.enemyMoveSpeedMultiplier,
        ),
        windupSec: enemy.windupSec,
    };
}
