import type { BuildingTemplateConfig, MvpBuildingId } from './balanceTypes';

export const BUILDING_TEMPLATES = {
    arcane_lab: {
        armor: 10,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'research',
        costCoins: 420,
        costLumber: 420,
        displayName: '아케인 생텀',
        footprintCells: { h: 3, w: 3 },
        hp: 1500,
        id: 'arcane_lab',
        originalCost: { gold: 2500, lumber: 2500 },
        originalRequires: ['h015'],
        providesResearch: [
            'dogSpeedClaw',
            'guardmanBoost',
            'soldierAttackSpeed',
            'automation',
        ],
        requires: ['family_temple'],
        source: {
            rawcode: 'h01H',
        },
        targetableByWolves: true,
    },
    barrier_magic: {
        armor: 8,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'wall',
        costCoins: 46,
        costLumber: 24,
        displayName: '마법의 결계',
        footprintCells: { h: 2, w: 1 },
        hp: 650,
        id: 'barrier_magic',
        originalCost: { gold: 150, lumber: 80 },
        originalRequires: ['h00C'],
        requires: ['workshop_lab'],
        source: {
            rawcode: 'h00Y',
        },
        targetableByWolves: true,
        upgradeTo: 'plasma_wall',
    },
    blacksmith: {
        armor: 5,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'research',
        costCoins: 70,
        costLumber: 35,
        displayName: '블랙스미스',
        footprintCells: { h: 3, w: 3 },
        hp: 300,
        id: 'blacksmith',
        originalCost: { gold: 300, lumber: 150 },
        originalRequires: ['h001'],
        providesResearch: [
            'meleeDamage',
            'soldierArmor',
            'rangedRange',
            'rangedDamage',
        ],
        requires: ['farm_house'],
        source: {
            rawcode: 'h00B',
        },
        targetableByWolves: true,
    },
    coop_basic: {
        armor: 2,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'economy',
        costCoins: 120,
        costLumber: 52,
        displayName: '닭장',
        footprintCells: { h: 3, w: 3 },
        hp: 200,
        id: 'coop_basic',
        originalCost: { gold: 700, lumber: 300 },
        originalRequires: ['h00H'],
        requires: ['town_hall'],
        source: {
            rawcode: 'h00N',
        },
        targetableByWolves: true,
        upgradeTo: 'coop_mid',
    },
    coop_high: {
        armor: 6,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'economy',
        costCoins: 205,
        costLumber: 136,
        displayName: '서양식양계장',
        footprintCells: { h: 3, w: 3 },
        hp: 600,
        id: 'coop_high',
        originalCost: { gold: 1200, lumber: 800 },
        originalRequires: ['h015'],
        providesResearch: ['coopProtection'],
        requires: ['family_temple'],
        source: {
            rawcode: 'h01Z',
        },
        targetableByWolves: true,
    },
    coop_mid: {
        armor: 4,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'economy',
        costCoins: 136,
        costLumber: 85,
        displayName: '훼리카나',
        footprintCells: { h: 3, w: 3 },
        hp: 400,
        id: 'coop_mid',
        originalCost: { gold: 800, lumber: 500 },
        originalRequires: ['h00C'],
        providesResearch: ['coopProtection'],
        requires: ['workshop_lab'],
        source: {
            rawcode: 'h00O',
        },
        targetableByWolves: true,
        upgradeTo: 'coop_high',
    },
    egg_storage: {
        armor: 0,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'economy',
        costCoins: 60,
        displayName: '알 보관소',
        footprintCells: { h: 2, w: 2 },
        hp: 100,
        id: 'egg_storage',
        originalCost: { gold: 250 },
        originalRequires: ['h001'],
        requires: ['farm_house'],
        source: {
            rawcode: 'h004',
        },
        targetableByWolves: true,
        upgradeTo: 'coop_basic',
    },
    family_temple: {
        armor: 9,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'core',
        costCoins: 205,
        costLumber: 205,
        displayName: '신전',
        footprintCells: { h: 4, w: 4 },
        hp: 800,
        id: 'family_temple',
        originalCost: { gold: 1200, lumber: 1200 },
        originalRequires: ['h01X', 'h00C'],
        produces: ['big_dog', 'H002', 'h01W', 'n003', 'n004'],
        requires: ['grand_market', 'workshop_lab'],
        source: {
            rawcode: 'h015',
        },
        targetableByWolves: true,
        upgradeTo: 'arcane_lab',
    },
    farm_house: {
        armor: 5,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'core',
        costCoins: 60,
        displayName: '농가',
        footprintCells: { h: 3, w: 3 },
        hp: 350,
        id: 'farm_house',
        originalCost: { gold: 250 },
        produces: ['dog', 'H002', 'h01W', 'n003', 'n004'],
        source: {
            rawcode: 'h001',
        },
        targetableByWolves: true,
        upgradeTo: 'town_hall',
    },
    fence_bronze: {
        armor: 2,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'wall',
        costCoins: 22,
        displayName: '청동 울타리',
        footprintCells: { h: 2, w: 1 },
        hp: 300,
        id: 'fence_bronze',
        originalCost: { gold: 70 },
        source: {
            rawcode: 'h00L',
        },
        targetableByWolves: true,
        upgradeTo: 'wall_stone',
    },
    fence_wood: {
        armor: 1,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'wall',
        costCoins: 8,
        displayName: '울타리',
        footprintCells: { h: 2, w: 1 },
        hp: 200,
        id: 'fence_wood',
        originalCost: { gold: 5 },
        source: {
            rawcode: 'h003',
        },
        targetableByWolves: true,
        upgradeTo: 'fence_bronze',
    },
    gate_wood: {
        armor: 7,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'gate',
        costCoins: 18,
        displayName: '대문',
        footprintCells: { h: 1, w: 2 },
        hp: 300,
        id: 'gate_wood',
        originalCost: { gold: 50 },
        originalRequires: ['h01H', 'h003', 'h006', 'h01I'],
        requires: ['arcane_lab', 'fence_wood'],
        source: {
            notes: [
                'High-confidence closed gate candidate. h00G is kept as a pathing variant, not an MVP template.',
            ],
            rawcode: 'h006',
        },
        targetableByWolves: true,
    },
    grand_market: {
        armor: 2,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'market',
        costCoins: 90,
        costLumber: 28,
        displayName: '대형 시장',
        footprintCells: { h: 3, w: 3 },
        hp: 250,
        id: 'grand_market',
        originalCost: { gold: 500, lumber: 150 },
        originalRequires: ['h005'],
        requires: ['market', 'well_basic'],
        source: {
            rawcode: 'h01X',
        },
        targetableByWolves: true,
    },
    lumber_mill: {
        armor: 0,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'economy',
        costCoins: 84,
        displayName: '럼버 밀',
        footprintCells: { h: 3, w: 3 },
        hp: 150,
        id: 'lumber_mill',
        originalCost: { gold: 350 },
        originalRequires: ['h001'],
        providesResearch: ['masonry'],
        requires: ['farm_house'],
        source: {
            rawcode: 'h00A',
        },
        targetableByWolves: true,
        upgradeTo: 'lumber_mill_mid',
    },
    lumber_mill_high: {
        armor: 0,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'economy',
        costCoins: 248,
        displayName: '럼버 밀 3단계',
        footprintCells: { h: 3, w: 3 },
        hp: 150,
        id: 'lumber_mill_high',
        originalCost: { gold: 1450 },
        originalRequires: ['h01H'],
        providesResearch: ['masonry'],
        requires: ['arcane_lab'],
        source: {
            rawcode: 'h00W',
        },
        targetableByWolves: true,
    },
    lumber_mill_mid: {
        armor: 0,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'economy',
        costCoins: 128,
        displayName: '럼버 밀 2단계',
        footprintCells: { h: 3, w: 3 },
        hp: 150,
        id: 'lumber_mill_mid',
        originalCost: { gold: 750 },
        originalRequires: ['h015'],
        providesResearch: ['masonry'],
        requires: ['family_temple'],
        source: {
            rawcode: 'h00J',
        },
        targetableByWolves: true,
        upgradeTo: 'lumber_mill_high',
    },
    market: {
        armor: 0,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'market',
        costCoins: 18,
        displayName: '시장',
        footprintCells: { h: 2, w: 2 },
        hp: 100,
        id: 'market',
        originalCost: { gold: 75 },
        source: {
            rawcode: 'h00E',
        },
        targetableByWolves: true,
        upgradeTo: 'grand_market',
    },
    mercenary_barracks: {
        armor: 5,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'barracks',
        costCoins: 84,
        costLumber: 24,
        displayName: '용병소',
        footprintCells: { h: 3, w: 3 },
        hp: 600,
        id: 'mercenary_barracks',
        originalCost: { gold: 350, lumber: 100 },
        originalRequires: ['h001'],
        produces: ['h009', 'h00V', 'hrtt'],
        requires: ['farm_house'],
        source: {
            rawcode: 'h026',
        },
        targetableByWolves: true,
    },
    plasma_wall: {
        armor: 20,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'wall',
        costCoins: 110,
        costLumber: 126,
        displayName: '플라즈마 벽',
        footprintCells: { h: 2, w: 1 },
        hp: 1600,
        id: 'plasma_wall',
        originalCost: { gold: 350, lumber: 400 },
        originalRequires: ['h01H'],
        requires: ['arcane_lab'],
        source: {
            notes: [
                'High-confidence final wall. Medium-confidence h014/h01D intermediate barriers are skipped in MVP.',
            ],
            rawcode: 'h01G',
        },
        targetableByWolves: true,
    },
    power_generator: {
        armor: 5,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'research',
        costCoins: 120,
        costLumber: 102,
        displayName: '발전기',
        footprintCells: { h: 2, w: 2 },
        hp: 500,
        id: 'power_generator',
        originalCost: { gold: 700, lumber: 600 },
        originalRequires: ['h00B'],
        providesResearch: [
            'guardTowerDamage',
            'arcaneTowerDamage',
            'towerSupportUpgrade',
        ],
        requires: ['blacksmith'],
        source: {
            rawcode: 'h01V',
        },
        targetableByWolves: true,
    },
    tower_arcane_grand: {
        armor: 13,
        attack: {
            cooldownSec: 0.7,
            damage: 76,
            rangePx: 360,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 230,
        costLumber: 176,
        displayName: '초대형 아케인 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 1000,
        id: 'tower_arcane_grand',
        originalCost: { gold: 1300, lumber: 1000 },
        originalRequires: ['h01H'],
        requires: ['arcane_lab'],
        source: {
            rawcode: 'h01K',
        },
        targetableByWolves: true,
    },
    tower_arcane_large: {
        armor: 9,
        attack: {
            cooldownSec: 0.7,
            damage: 54,
            rangePx: 330,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 160,
        costLumber: 142,
        displayName: '대형 아케인 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 800,
        id: 'tower_arcane_large',
        originalCost: { gold: 900, lumber: 800 },
        originalRequires: ['h015'],
        requires: ['family_temple'],
        source: {
            rawcode: 'h017',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_arcane_grand',
    },
    tower_arcane_medium: {
        armor: 8,
        attack: {
            cooldownSec: 0.7,
            damage: 38,
            rangePx: 300,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 100,
        costLumber: 90,
        displayName: '중형 아케인 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 650,
        id: 'tower_arcane_medium',
        originalCost: { gold: 500, lumber: 450 },
        originalRequires: ['h00C'],
        requires: ['workshop_lab'],
        source: {
            rawcode: 'h008',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_arcane_large',
    },
    tower_arcane_small: {
        armor: 7,
        attack: {
            cooldownSec: 0.7,
            damage: 26,
            rangePx: 270,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 76,
        costLumber: 66,
        displayName: '소형 아케인 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 400,
        id: 'tower_arcane_small',
        originalCost: { gold: 400, lumber: 350 },
        originalRequires: ['h00H'],
        requires: ['town_hall'],
        source: {
            rawcode: 'h016',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_arcane_medium',
    },
    tower_guard_black: {
        armor: 12,
        attack: {
            cooldownSec: 0.9,
            damage: 64,
            rangePx: 345,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 220,
        costLumber: 264,
        displayName: '칠흑의 가드 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 900,
        id: 'tower_guard_black',
        originalCost: { gold: 1000, lumber: 1200 },
        originalRequires: ['h01H'],
        requires: ['arcane_lab'],
        source: {
            rawcode: 'h01J',
        },
        targetableByWolves: true,
    },
    tower_guard_grand: {
        armor: 9,
        attack: {
            cooldownSec: 0.9,
            damage: 46,
            rangePx: 315,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 132,
        costLumber: 106,
        displayName: '초대형 가드 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 750,
        id: 'tower_guard_grand',
        originalCost: { gold: 750, lumber: 600 },
        originalRequires: ['h015'],
        requires: ['family_temple'],
        source: {
            rawcode: 'h00R',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_guard_black',
    },
    tower_guard_large: {
        armor: 8,
        attack: {
            cooldownSec: 0.8,
            damage: 40,
            rangePx: 285,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 76,
        costLumber: 54,
        displayName: '대형 가드 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 550,
        id: 'tower_guard_large',
        originalCost: { gold: 350, lumber: 250 },
        originalRequires: ['h00C'],
        requires: ['workshop_lab'],
        source: {
            rawcode: 'h00Z',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_guard_grand',
    },
    tower_guard_medium: {
        armor: 7,
        attack: {
            cooldownSec: 0.85,
            damage: 34,
            rangePx: 255,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 56,
        costLumber: 34,
        displayName: '중형 가드 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 400,
        id: 'tower_guard_medium',
        originalCost: { gold: 250, lumber: 150 },
        originalRequires: ['h00H'],
        requires: ['town_hall'],
        source: {
            rawcode: 'h00Q',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_guard_large',
    },
    tower_guard_small: {
        armor: 6,
        attack: {
            cooldownSec: 0.9,
            damage: 22,
            rangePx: 225,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 44,
        costLumber: 18,
        displayName: '소형 가드 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 300,
        id: 'tower_guard_small',
        originalCost: { gold: 250, lumber: 100 },
        originalRequires: ['h00A'],
        requires: ['lumber_mill'],
        source: {
            rawcode: 'h007',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_guard_medium',
    },
    tower_scout: {
        armor: 5,
        attack: {
            cooldownSec: 1.05,
            damage: 14,
            rangePx: 195,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'tower',
        costCoins: 32,
        displayName: '스카우트 타워',
        footprintCells: { h: 2, w: 2 },
        hp: 275,
        id: 'tower_scout',
        originalCost: { gold: 125 },
        source: {
            rawcode: 'h00D',
        },
        targetableByWolves: true,
        upgradeTo: 'tower_guard_small',
    },
    town_hall: {
        armor: 7,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'core',
        costCoins: 80,
        costLumber: 40,
        displayName: '마을회관',
        footprintCells: { h: 4, w: 4 },
        hp: 600,
        id: 'town_hall',
        originalCost: { gold: 400, lumber: 200 },
        originalRequires: ['H002'],
        produces: ['dog', 'H002', 'h01W', 'n003', 'n004'],
        requires: ['farm_house'],
        source: {
            rawcode: 'h00H',
        },
        targetableByWolves: true,
        upgradeTo: 'family_temple',
    },
    wall_stone: {
        armor: 5,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'wall',
        costCoins: 34,
        costLumber: 14,
        displayName: '돌 벽',
        footprintCells: { h: 2, w: 1 },
        hp: 450,
        id: 'wall_stone',
        originalCost: { gold: 100, lumber: 40 },
        originalRequires: ['h00H'],
        requires: ['town_hall'],
        source: {
            rawcode: 'h00K',
        },
        targetableByWolves: true,
        upgradeTo: 'barrier_magic',
    },
    well_basic: {
        armor: 100,
        aura: {
            amountPerSec: 2,
            kind: 'heal',
            rangePx: 96,
        },
        blocksPath: true,
        buildTimeSec: 0,
        category: 'support',
        costCoins: 30,
        displayName: '우물',
        footprintCells: { h: 2, w: 2 },
        hp: 100,
        id: 'well_basic',
        originalCost: { gold: 150 },
        originalRequires: ['h001'],
        requires: ['farm_house'],
        source: {
            rawcode: 'h00M',
        },
        targetableByWolves: true,
    },
    workshop_lab: {
        armor: 5,
        blocksPath: true,
        buildTimeSec: 0,
        category: 'research',
        costCoins: 136,
        costLumber: 85,
        displayName: '워크샵',
        footprintCells: { h: 3, w: 3 },
        hp: 700,
        id: 'workshop_lab',
        originalCost: { gold: 800, lumber: 500 },
        originalRequires: ['h00H'],
        produces: ['n005', 'h00U', 'h00P', 'n00Y'],
        providesResearch: ['workshopSpecial'],
        requires: ['town_hall'],
        source: {
            rawcode: 'h00C',
        },
        targetableByWolves: true,
    },
} satisfies Record<MvpBuildingId, BuildingTemplateConfig>;
