import type { VehicleEngineProfile } from './engineProfile';
import type { PlayerVehicleControllerConfig } from './playerVehicleController';
import { createRuntimePlayerVehicleConfig } from './runtimeConfig';

export const PLAYER_BRAKE_SPEED = 0;
export const PLAYER_BRAKING = 330;
export const PLAYER_BRAKE_RELEASE_RESPONSE = 13;
export const PLAYER_BRAKE_RESPONSE = 8;
export const PLAYER_CENTERING_RESPONSE = 6;
export const PLAYER_CENTERING_COUNTER_HOLD_DURATION = 0.18;
export const PLAYER_CENTERING_COUNTER_START_SCALE = 0.58;
export const PLAYER_CENTERING_INPUT_HOLD_SCALE = 0.35;
export const PLAYER_CENTERING_NEUTRAL_INWARD_VELOCITY_CAP = 20;
export const PLAYER_CENTERING_RELEASE_DELAY = 0.18;
export const PLAYER_CENTERING_RELEASE_SCALE_RESPONSE = 0.8;
export const PLAYER_CENTERING_RELEASE_SCALE = 0.45;
export const PLAYER_CENTERING_SCALE_RESPONSE = 4.8;
export const PLAYER_CRUISE_SPEED = 0;
export const PLAYER_ACCEL_SPEED = 760;
export const PLAYER_CORNER_EASY_INTENSITY_THRESHOLD = 0.34;
export const PLAYER_CORNER_EASY_SPEED_LOSS_SCALE = 0.95;
export const PLAYER_CORNER_LINE_SPEED_BONUS = 70;
export const PLAYER_CORNER_LINE_TARGET_OFFSET = 260;
export const PLAYER_CORNER_SEVERE_LINE_SCRUB_SCALE = 1.2;
export const PLAYER_CORNER_SEVERE_OVERSPEED_FULL_RATIO = 1.45;
export const PLAYER_CORNER_SEVERE_OVERSPEED_SCRUB = 140;
export const PLAYER_CORNER_SEVERE_OVERSPEED_START_RATIO = 1.18;
export const PLAYER_CORNER_SHARP_INTENSITY_THRESHOLD = 0.7;
export const PLAYER_CORNER_SHARP_LINE_REWARD_SCALE = 1.35;
export const PLAYER_CORNER_SHARP_SPEED_LOSS_SCALE = 1.18;
export const PLAYER_CORNER_SPEED_PULL = 100;
export const PLAYER_DOWNHILL_CORNER_BUDGET_MAX_REDUCTION = 0;
export const PLAYER_DOWNHILL_CORNER_BUDGET_SLOPE_ACCELERATION = 65;
export const PLAYER_DOWNHILL_CORNER_LATERAL_SCALE = 1.3;
export const PLAYER_DOWNHILL_CORNER_OVERSPEED_SCRUB = 0;
export const PLAYER_INPUT_RESPONSE = 18;
export const PLAYER_LAUNCH_THROTTLE_FULL_SPEED_RATIO = 1;
export const PLAYER_LAUNCH_THROTTLE_MIN_RATIO = 0.5;
export const PLAYER_MAX_ROAD_OFFSET = 700;
export const PLAYER_OVERSPEED_UNDERSTEER_MAX = 0.62;
export const PLAYER_OVERSPEED_EASY_UNDERSTEER_FULL_RATIO = 0.2;
export const PLAYER_OVERSPEED_EASY_UNDERSTEER_SCALE = 0.3;
export const PLAYER_OVERSPEED_MEDIUM_UNDERSTEER_SCALE = 0.58;
export const PLAYER_OVERSPEED_UNDERSTEER_MIN_STEER_INPUT = 0.08;
export const PLAYER_OVERSPEED_UNDERSTEER_STEER_INPUT_FULL = 0.45;
export const PLAYER_OVERSPEED_UNDERSTEER_LIFT_TARGET_SCALE = 0.55;
export const PLAYER_OVERSPEED_UNDERSTEER_BRAKE_TARGET_SCALE = 0.28;
export const PLAYER_OVERSPEED_EASY_LATERAL_SCALE = 4;
export const PLAYER_OVERSPEED_EASY_ROAD_MAX_RATIO = 0.22;
export const PLAYER_OVERSPEED_MEDIUM_LATERAL_SCALE = 1.15;
export const PLAYER_OVERSPEED_MEDIUM_ROAD_MAX_RATIO = 0.42;
export const PLAYER_OVERSPEED_SAFETY_MARGIN_START_RATIO = 0.16;
// A substantial exit cost should arrive well before the shoulder, so a fast
// grip line has to leave room for the corner rather than occupy all of it.
export const PLAYER_OVERSPEED_SAFETY_MARGIN_FULL_RATIO = 0.32;
export const PLAYER_OVERSPEED_SAFETY_MARGIN_SCRUB = 75;
export const PLAYER_OVERSPEED_SHARP_LATERAL_SCALE = 1.55;
export const PLAYER_OVERSPEED_SHARP_SPEED_SCRUB_SCALE = 1.35;
export const PLAYER_OVERSPEED_SHARP_UNDERSTEER_SCALE = 1;
export const PLAYER_OVERSPEED_UNDERSTEER_ROAD_BUILD_RATE = 2.2;
export const PLAYER_OVERSPEED_UNDERSTEER_ROAD_MAX_RATIO = 0.54;
export const PLAYER_OVERSPEED_UNDERSTEER_ROAD_RECOVERY_RATE = 7.5;
export const PLAYER_OVERSPEED_UNDERSTEER_ROAD_SPEED_RATE = 0.72;
export const PLAYER_OVERSPEED_UNDERSTEER_RATIO_BUILD_RATE = 2.8;
export const PLAYER_OVERSPEED_UNDERSTEER_RATIO_RECOVERY_RATE = 4.5;
export const PLAYER_OVERSPEED_UNDERSTEER_SPEED_SCRUB = 28;
export const PLAYER_OVERSPEED_UNDERSTEER_SPEED_WINDOW = 150;
export const PLAYER_ROAD_ANCHOR_DISTANCE = 640;
export const PLAYER_ROAD_CONTACT_DISTANCE = 260;
export const PLAYER_HEADLIGHT_AIM_FINE_STEER_PX = 14;
export const PLAYER_HEADLIGHT_AIM_FINE_ATTACK_SECONDS = 0.05;
export const PLAYER_HEADLIGHT_AIM_FINE_RETURN_SECONDS = 0.1;
export const PLAYER_HEADLIGHT_CURVE_INTENT_DRIFT_ROAD_WEIGHT = 0.3;
export const PLAYER_HEADLIGHT_CURVE_INTENT_GRIP_ROAD_WEIGHT = 0.55;
export const PLAYER_HEADLIGHT_AIM_MAX_PX = 72;
export const PLAYER_HEADLIGHT_AIM_MAX_ROAD_PX = 54;
export const PLAYER_HEADLIGHT_AIM_ROAD_ASSIST_RESPONSE_SECONDS = 0.2;
export const PLAYER_HEADLIGHT_AIM_ROAD_STRONG_POSE_WEIGHT = 0.1;
export const PLAYER_HEADLIGHT_AIM_ROAD_WEAK_POSE_WEIGHT = 0.35;
export const PLAYER_HEADLIGHT_FOOTPRINT_FALLBACK = {
    farHalfWidthRatio: 0.125,
    nearPaddingPx: 4,
    reachRatio: 0.098,
};
export const PLAYER_SCREEN_ANCHOR_RATIO = 0.88;
export const PLAYER_SHADOW_BASELINE_Y_OFFSET = 0.028;
export const PLAYER_SHADOW_MAX_ALPHA = 0.18;
export const PLAYER_SHADOW_SOFT_ALPHA = 0.24;
export const PLAYER_SILHOUETTE_SHADOW_ALPHA = 0.48;
export const PLAYER_STEER_ACCELERATION = 1650;
export const PLAYER_STEER_DAMPING = 9.2;
export const PLAYER_VEHICLE_VIEWPORT_RATIO = 0.34;
export const PLAYER_VEHICLE_MIN_SIZE = 220;
export const PLAYER_VEHICLE_MAX_SIZE = 360;
export const PLAYER_VEHICLE_ROTATION_DEG = 3.5;
export const PLAYER_VEHICLE_ROAD_SCALE_DEAD_ZONE_RATIO = 0.02;
export const PLAYER_VEHICLE_ROAD_SCALE_MAX = 1.08;
export const PLAYER_VEHICLE_ROAD_SCALE_MIN = 0.92;
export const PLAYER_VEHICLE_ROAD_SCALE_RESPONSE_SECONDS = 0.7;
export const PLAYER_VEHICLE_ROAD_TARGET_RATIO = 0.54;
export const PLAYER_STEER_WEAK_THRESHOLD = 0.14;
export const PLAYER_TERRAIN_CUE_THRESHOLD = 24;
export const PLAYER_CONTACT_TERRAIN_CUE_THRESHOLD = 8;
export const PLAYER_MAX_TERRAIN_SCREEN_Y_SHIFT = 18;
export const PLAYER_TERRAIN_SCALE_INTENSITY = 0.045;
export const PLAYER_CURVE_SCREEN_BIAS = 8;
export const PLAYER_CORNER_INERTIA_BUILD_RATE = 240;
export const PLAYER_CORNER_INERTIA_MAX_LATERAL_SPEED = 265;
export const PLAYER_CORNER_INERTIA_RECOVERY_RATE = 320;
export const PLAYER_CURVE_STEERING_CUE = 0.06;
export const PLAYER_DRIFT_BUILD_RATE = 2.8;
export const PLAYER_DRIFT_DECAY_RATE = 2.6;
export const PLAYER_DRIFT_ENTRY_SPEED_LOSS = 16;
export const PLAYER_DRIFT_ENTRY_LATERAL_KICK = 190;
export const PLAYER_DRIFT_BREAKAWAY_DURATION = 0.22;
export const PLAYER_DRIFT_BRAKE_ENTRY_PRESSURE = 0.64;
export const PLAYER_DRIFT_BRAKE_ENTRY_SPEED_LOSS = 14;
export const PLAYER_DRIFT_LIFT_ENTRY_SPEED_LOSS = 22;
export const PLAYER_DRIFT_EASY_ENTRY_SPEED_LOSS_SCALE = 0.55;
export const PLAYER_DRIFT_SHARP_ENTRY_SPEED_LOSS_SCALE = 1.25;
export const PLAYER_DRIFT_OUTSIDE_LINE_OVERSPEED_PULL = 0.65;
export const PLAYER_DRIFT_OUTSIDE_LINE_SCRUB_SCALE = 0.55;
export const PLAYER_DRIFT_EXIT_REACCEL_DELAY = 0.24;
export const PLAYER_DRIFT_THROTTLE_GRACE_DURATION = 0.28;
export const PLAYER_DRIFT_THROTTLE_LIFT_RATIO = 0.44;
export const PLAYER_DRIFT_COUNTER_NEUTRAL_DURATION = 0.08;
export const PLAYER_DRIFT_LATERAL_DAMPING = 1.9;
export const PLAYER_DRIFT_LATERAL_MAX_SPEED = 230;
export const PLAYER_DRIFT_COUNTER_STEER_LATERAL_SCALE = 0.42;
export const PLAYER_DRIFT_COUNTER_STEER_LATERAL_SUSTAIN_SCALE = 0.58;
export const PLAYER_DRIFT_COUNTER_STEER_LATERAL_VELOCITY_CAP = 52;
// Counter steer should trim the existing slide, not pull the car back to grip.
export const PLAYER_DRIFT_COUNTER_TRIM_DURATION = 0.65;
export const PLAYER_DRIFT_COUNTER_TRIM_MAX_RATIO = 0.62;
export const PLAYER_DRIFT_COUNTER_TRIM_RESPONSE = 7;
export const PLAYER_DRIFT_COUNTER_TRIM_RELEASE_RESPONSE = 4;
export const PLAYER_DRIFT_SUSTAIN_ACCELERATION = 300;
export const PLAYER_DRIFT_TRANSITION_ARM_DURATION = 0.12;
export const PLAYER_DRIFT_TRANSITION_INPUT_WINDOW = 0.42;
export const PLAYER_DRIFT_TRANSITION_KICK = 120;
export const PLAYER_DRIFT_MAX_SLIP_ANGLE = 10;
export const PLAYER_DRIFT_MIN_CORNER_INTENSITY = 0.38;
export const PLAYER_DRIFT_MIN_SPEED_RATIO = 0.55;
export const PLAYER_DRIFT_MIN_STEER_INPUT = 0.6;
export const PLAYER_DRIFT_RECOVERY_RATE = 2.3;
export const PLAYER_CURVE_STEERING_HIGH_SPEED_DROP = 0.42;
export const PLAYER_HIGH_SPEED_INPUT_RESPONSE_DROP = 0.28;
export const PLAYER_HIGH_SPEED_LATERAL_VELOCITY_CAP = 70;
export const PLAYER_HIGH_SPEED_STEERING_SLEW_RATE = 5.6;
export const PLAYER_HIGH_SPEED_STEER_FORCE_DROP = 0.54;
export const PLAYER_HIGH_SPEED_STEER_VISUAL_DROP = 0.43;
export const PLAYER_GRIP_STEER_ANGLE_HIGH_SPEED_CAP = 0.72;
export const PLAYER_GRIP_STEER_ANGLE_HIGH_SPEED_START_RATIO = 0.55;
export const PLAYER_GRIP_COUNTER_ROAD_CENTERING_SCALE = 0.1;
export const PLAYER_GRIP_COUNTER_ROAD_LATERAL_BUILD_RATE = 180;
export const PLAYER_GRIP_COUNTER_ROAD_LATERAL_MAX_SPEED = 96;
export const PLAYER_GRIP_COUNTER_ROAD_LATERAL_RECOVERY_RATE = 150;
export const PLAYER_GRIP_COUNTER_ROAD_SPEED_SCRUB = 72;
export const PLAYER_HIGH_SPEED_STEER_WEAK_THRESHOLD = 0.22;
export const PLAYER_HIGH_SPEED_VISUAL_STEERING_SCALE = 1;
export const PLAYER_STEERING_VELOCITY_CUE = 0.2;
export const PLAYER_STEERING_SPEED_SCRUB = 64;
export const PLAYER_STEERING_SPEED_SCRUB_THRESHOLD = 0.22;
export const PLAYER_ENGINE_ACCELERATION = 82;
export const PLAYER_ENGINE_BRAKE_DECELERATION = 26;
export const PLAYER_ROLLING_RESISTANCE = 14;
export const PLAYER_AERO_DRAG = 0.000007661283025835461;
export const PLAYER_GRAVITY_ACCELERATION = 360;
export const PLAYER_MAX_SLOPE_ACCELERATION = 115;
export const PLAYER_SLOPE_SAMPLE_DISTANCE = 720;
export const PLAYER_RPM_IDLE = 1100;
export const PLAYER_RPM_REDLINE = 7200;
export const PLAYER_RPM_RESPONSE = 7;
export function createPlayerVehicleRuntimeConfig(params: URLSearchParams, engineProfile: VehicleEngineProfile): PlayerVehicleControllerConfig {
    return createRuntimePlayerVehicleConfig(params, {
    accelSpeed: PLAYER_ACCEL_SPEED,
    aeroDrag: PLAYER_AERO_DRAG,
    brakeSpeed: PLAYER_BRAKE_SPEED,
    braking: PLAYER_BRAKING,
    brakeReleaseResponse: PLAYER_BRAKE_RELEASE_RESPONSE,
    brakeResponse: PLAYER_BRAKE_RESPONSE,
    centeringResponse: PLAYER_CENTERING_RESPONSE,
    centeringCounterHoldDuration: PLAYER_CENTERING_COUNTER_HOLD_DURATION,
    centeringCounterStartScale: PLAYER_CENTERING_COUNTER_START_SCALE,
    centeringInputHoldScale: PLAYER_CENTERING_INPUT_HOLD_SCALE,
    centeringNeutralInwardVelocityCap: PLAYER_CENTERING_NEUTRAL_INWARD_VELOCITY_CAP,
    centeringReleaseDelay: PLAYER_CENTERING_RELEASE_DELAY,
    centeringReleaseScaleResponse: PLAYER_CENTERING_RELEASE_SCALE_RESPONSE,
    centeringReleaseScale: PLAYER_CENTERING_RELEASE_SCALE,
    centeringScaleResponse: PLAYER_CENTERING_SCALE_RESPONSE,
    cornerEasyIntensityThreshold: PLAYER_CORNER_EASY_INTENSITY_THRESHOLD,
    cornerEasySpeedLossScale: PLAYER_CORNER_EASY_SPEED_LOSS_SCALE,
    cornerLineSpeedBonus: PLAYER_CORNER_LINE_SPEED_BONUS,
    cornerLineTargetOffset: PLAYER_CORNER_LINE_TARGET_OFFSET,
    cornerSevereLineScrubScale: PLAYER_CORNER_SEVERE_LINE_SCRUB_SCALE,
    cornerSevereOverspeedFullRatio: PLAYER_CORNER_SEVERE_OVERSPEED_FULL_RATIO,
    cornerSevereOverspeedScrub: PLAYER_CORNER_SEVERE_OVERSPEED_SCRUB,
    cornerSevereOverspeedStartRatio: PLAYER_CORNER_SEVERE_OVERSPEED_START_RATIO,
    cornerSharpIntensityThreshold: PLAYER_CORNER_SHARP_INTENSITY_THRESHOLD,
    cornerSharpLineRewardScale: PLAYER_CORNER_SHARP_LINE_REWARD_SCALE,
    cornerSharpSpeedLossScale: PLAYER_CORNER_SHARP_SPEED_LOSS_SCALE,
    cornerSpeedPull: PLAYER_CORNER_SPEED_PULL,
    cornerInertiaBuildRate: PLAYER_CORNER_INERTIA_BUILD_RATE,
    cornerInertiaMaxLateralSpeed: PLAYER_CORNER_INERTIA_MAX_LATERAL_SPEED,
    cornerInertiaRecoveryRate: PLAYER_CORNER_INERTIA_RECOVERY_RATE,
    downhillCornerBudgetMaxReduction: PLAYER_DOWNHILL_CORNER_BUDGET_MAX_REDUCTION,
    downhillCornerBudgetSlopeAcceleration: PLAYER_DOWNHILL_CORNER_BUDGET_SLOPE_ACCELERATION,
    downhillCornerLateralScale: PLAYER_DOWNHILL_CORNER_LATERAL_SCALE,
    downhillCornerOverspeedScrub: PLAYER_DOWNHILL_CORNER_OVERSPEED_SCRUB,
    curveSteeringHighSpeedDrop: PLAYER_CURVE_STEERING_HIGH_SPEED_DROP,
    curveSteeringCue: PLAYER_CURVE_STEERING_CUE,
    driftBuildRate: PLAYER_DRIFT_BUILD_RATE,
    driftDecayRate: PLAYER_DRIFT_DECAY_RATE,
    driftEntrySpeedLoss: PLAYER_DRIFT_ENTRY_SPEED_LOSS,
    driftEntryLateralKick: PLAYER_DRIFT_ENTRY_LATERAL_KICK,
    driftBreakawayDuration: PLAYER_DRIFT_BREAKAWAY_DURATION,
    driftBrakeEntryPressure: PLAYER_DRIFT_BRAKE_ENTRY_PRESSURE,
    driftBrakeEntrySpeedLoss: PLAYER_DRIFT_BRAKE_ENTRY_SPEED_LOSS,
    driftLiftEntrySpeedLoss: PLAYER_DRIFT_LIFT_ENTRY_SPEED_LOSS,
    driftEasyEntrySpeedLossScale: PLAYER_DRIFT_EASY_ENTRY_SPEED_LOSS_SCALE,
    driftSharpEntrySpeedLossScale: PLAYER_DRIFT_SHARP_ENTRY_SPEED_LOSS_SCALE,
    driftOutsideLineOverspeedPull: PLAYER_DRIFT_OUTSIDE_LINE_OVERSPEED_PULL,
    driftOutsideLineScrubScale: PLAYER_DRIFT_OUTSIDE_LINE_SCRUB_SCALE,
    driftExitReaccelDelay: PLAYER_DRIFT_EXIT_REACCEL_DELAY,
    driftThrottleGraceDuration: PLAYER_DRIFT_THROTTLE_GRACE_DURATION,
    driftThrottleLiftRatio: PLAYER_DRIFT_THROTTLE_LIFT_RATIO,
    driftCounterNeutralDuration: PLAYER_DRIFT_COUNTER_NEUTRAL_DURATION,
    driftLateralDamping: PLAYER_DRIFT_LATERAL_DAMPING,
    driftLateralMaxSpeed: PLAYER_DRIFT_LATERAL_MAX_SPEED,
    driftCounterSteerLateralScale: PLAYER_DRIFT_COUNTER_STEER_LATERAL_SCALE,
    driftCounterSteerLateralSustainScale: PLAYER_DRIFT_COUNTER_STEER_LATERAL_SUSTAIN_SCALE,
    driftCounterSteerLateralVelocityCap: PLAYER_DRIFT_COUNTER_STEER_LATERAL_VELOCITY_CAP,
    driftCounterTrimDuration: PLAYER_DRIFT_COUNTER_TRIM_DURATION,
    driftCounterTrimMaxRatio: PLAYER_DRIFT_COUNTER_TRIM_MAX_RATIO,
    driftCounterTrimResponse: PLAYER_DRIFT_COUNTER_TRIM_RESPONSE,
    driftCounterTrimReleaseResponse: PLAYER_DRIFT_COUNTER_TRIM_RELEASE_RESPONSE,
    driftSustainAcceleration: PLAYER_DRIFT_SUSTAIN_ACCELERATION,
    driftTransitionArmDuration: PLAYER_DRIFT_TRANSITION_ARM_DURATION,
    driftTransitionInputWindow: PLAYER_DRIFT_TRANSITION_INPUT_WINDOW,
    driftTransitionKick: PLAYER_DRIFT_TRANSITION_KICK,
    driftMaxSlipAngle: PLAYER_DRIFT_MAX_SLIP_ANGLE,
    driftMinCornerIntensity: PLAYER_DRIFT_MIN_CORNER_INTENSITY,
    driftMinSpeedRatio: PLAYER_DRIFT_MIN_SPEED_RATIO,
    driftMinSteerInput: PLAYER_DRIFT_MIN_STEER_INPUT,
    driftRecoveryRate: PLAYER_DRIFT_RECOVERY_RATE,
    engineAcceleration: PLAYER_ENGINE_ACCELERATION,
    engineBrakeDeceleration: PLAYER_ENGINE_BRAKE_DECELERATION,
    engineProfile,
    gripCounterRoadCenteringScale: PLAYER_GRIP_COUNTER_ROAD_CENTERING_SCALE,
    gripCounterRoadLateralBuildRate: PLAYER_GRIP_COUNTER_ROAD_LATERAL_BUILD_RATE,
    gripCounterRoadLateralMaxSpeed: PLAYER_GRIP_COUNTER_ROAD_LATERAL_MAX_SPEED,
    gripCounterRoadLateralRecoveryRate: PLAYER_GRIP_COUNTER_ROAD_LATERAL_RECOVERY_RATE,
    gripCounterRoadSpeedScrub: PLAYER_GRIP_COUNTER_ROAD_SPEED_SCRUB,
    highSpeedInputResponseDrop: PLAYER_HIGH_SPEED_INPUT_RESPONSE_DROP,
    highSpeedLateralVelocityCap: PLAYER_HIGH_SPEED_LATERAL_VELOCITY_CAP,
    highSpeedSteeringSlewRate: PLAYER_HIGH_SPEED_STEERING_SLEW_RATE,
    highSpeedSteerForceDrop: PLAYER_HIGH_SPEED_STEER_FORCE_DROP,
    highSpeedSteerVisualDrop: PLAYER_HIGH_SPEED_STEER_VISUAL_DROP,
    gripSteerAngleHighSpeedCap: PLAYER_GRIP_STEER_ANGLE_HIGH_SPEED_CAP,
    gripSteerAngleHighSpeedStartRatio: PLAYER_GRIP_STEER_ANGLE_HIGH_SPEED_START_RATIO,
    inputResponse: PLAYER_INPUT_RESPONSE,
    launchThrottleFullSpeedRatio: PLAYER_LAUNCH_THROTTLE_FULL_SPEED_RATIO,
    launchThrottleMinRatio: PLAYER_LAUNCH_THROTTLE_MIN_RATIO,
    maxRoadOffset: PLAYER_MAX_ROAD_OFFSET,
    overspeedUndersteerMax: PLAYER_OVERSPEED_UNDERSTEER_MAX,
    overspeedEasyUndersteerFullRatio: PLAYER_OVERSPEED_EASY_UNDERSTEER_FULL_RATIO,
    overspeedEasyUndersteerScale: PLAYER_OVERSPEED_EASY_UNDERSTEER_SCALE,
    overspeedMediumUndersteerScale: PLAYER_OVERSPEED_MEDIUM_UNDERSTEER_SCALE,
    overspeedUndersteerMinSteerInput: PLAYER_OVERSPEED_UNDERSTEER_MIN_STEER_INPUT,
    overspeedUndersteerSteerInputFull: PLAYER_OVERSPEED_UNDERSTEER_STEER_INPUT_FULL,
    overspeedUndersteerLiftTargetScale: PLAYER_OVERSPEED_UNDERSTEER_LIFT_TARGET_SCALE,
    overspeedUndersteerBrakeTargetScale: PLAYER_OVERSPEED_UNDERSTEER_BRAKE_TARGET_SCALE,
    overspeedEasyLateralScale: PLAYER_OVERSPEED_EASY_LATERAL_SCALE,
    overspeedEasyRoadMaxRatio: PLAYER_OVERSPEED_EASY_ROAD_MAX_RATIO,
    overspeedMediumLateralScale: PLAYER_OVERSPEED_MEDIUM_LATERAL_SCALE,
    overspeedMediumRoadMaxRatio: PLAYER_OVERSPEED_MEDIUM_ROAD_MAX_RATIO,
    overspeedSafetyMarginStartRatio: PLAYER_OVERSPEED_SAFETY_MARGIN_START_RATIO,
    overspeedSafetyMarginFullRatio: PLAYER_OVERSPEED_SAFETY_MARGIN_FULL_RATIO,
    overspeedSafetyMarginScrub: PLAYER_OVERSPEED_SAFETY_MARGIN_SCRUB,
    overspeedSharpLateralScale: PLAYER_OVERSPEED_SHARP_LATERAL_SCALE,
    overspeedSharpSpeedScrubScale: PLAYER_OVERSPEED_SHARP_SPEED_SCRUB_SCALE,
    overspeedSharpUndersteerScale: PLAYER_OVERSPEED_SHARP_UNDERSTEER_SCALE,
    overspeedUndersteerRoadBuildRate: PLAYER_OVERSPEED_UNDERSTEER_ROAD_BUILD_RATE,
    overspeedUndersteerRoadMaxRatio: PLAYER_OVERSPEED_UNDERSTEER_ROAD_MAX_RATIO,
    overspeedUndersteerRoadRecoveryRate: PLAYER_OVERSPEED_UNDERSTEER_ROAD_RECOVERY_RATE,
    overspeedUndersteerRoadSpeedRate: PLAYER_OVERSPEED_UNDERSTEER_ROAD_SPEED_RATE,
    overspeedUndersteerRatioBuildRate: PLAYER_OVERSPEED_UNDERSTEER_RATIO_BUILD_RATE,
    overspeedUndersteerRatioRecoveryRate: PLAYER_OVERSPEED_UNDERSTEER_RATIO_RECOVERY_RATE,
    overspeedUndersteerSpeedScrub: PLAYER_OVERSPEED_UNDERSTEER_SPEED_SCRUB,
    overspeedUndersteerSpeedWindow: PLAYER_OVERSPEED_UNDERSTEER_SPEED_WINDOW,
    rollingResistance: PLAYER_ROLLING_RESISTANCE,
    rpmIdle: PLAYER_RPM_IDLE,
    rpmRedline: PLAYER_RPM_REDLINE,
    rpmResponse: PLAYER_RPM_RESPONSE,
    steerAcceleration: PLAYER_STEER_ACCELERATION,
    steerDamping: PLAYER_STEER_DAMPING,
    steeringSpeedScrub: PLAYER_STEERING_SPEED_SCRUB,
    steeringSpeedScrubThreshold: PLAYER_STEERING_SPEED_SCRUB_THRESHOLD,
    steeringVelocityCue: PLAYER_STEERING_VELOCITY_CUE,
});
}
