/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/resident-verification/wrangler.jsonc --include-runtime=false workers/resident-verification/src/worker-configuration.d.ts` (hash: f816c48881bc7eaf728161b143341613)
interface __BaseEnv_Env {
	RESIDENT_ENTRY_PASSWORD: string;
	KAKAO_OPEN_CHAT_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESIDENT_ENTRY_PASSWORD" | "KAKAO_OPEN_CHAT_URL">> {}
}
