export type RestaurantCategory = '한식' | '고기' | '중식' | '일식' | '양식' | '카페';

export interface NaesonRestaurant {
    name: string;
    category: RestaurantCategory;
    emoji: string;
    location: string;
    menus: string[];
    note: string;
    sources: string[];
    isNew?: boolean;
    needsLocationCheck?: boolean;
    searchQuery?: string;
}

export const naesonRestaurants: NaesonRestaurant[] = [
    {
        name: '소코아 의왕점',
        category: '양식',
        emoji: '🍛',
        location: '의왕시 복지로 118 · 계원예대 인근',
        menus: ['카레', '오므라이스', '에비카레'],
        note: '카레 메뉴가 특히 좋았다는 이웃 추천',
        sources: ['101동', '105동'],
    },
    {
        name: '원조 부안집',
        category: '고기',
        emoji: '🥩',
        location: '의왕시 포일로 일대 · 벨포레 인근',
        menus: ['숙성 삼겹살', '쫀득살', '김치찌개'],
        note: '고기 먹는 날 떠올리기 좋은 곳',
        sources: ['105동'],
        needsLocationCheck: true,
        searchQuery: '원조부안집 의왕 포일동',
    },
    {
        name: '황제짬뽕',
        category: '중식',
        emoji: '🍜',
        location: '의왕시 갈미2로 30 · 미광프라자',
        menus: ['황제짬뽕', '짜장면', '탕수육'],
        note: '칼칼한 국물이 생각날 때',
        sources: ['105동'],
    },
    {
        name: '스시상',
        category: '일식',
        emoji: '🍣',
        location: '의왕시 갈미2로 34 · 주노프라자 103호',
        menus: ['모둠초밥', '회정식', '회덮밥'],
        note: '초밥과 회 메뉴를 함께 고르기 좋은 곳',
        sources: ['105동'],
    },
    {
        name: '마이그래니스',
        category: '카페',
        emoji: '☕',
        location: '의왕시 내손중앙로 7',
        menus: ['커피', '디저트'],
        note: '동네에서 가볍게 쉬어가기 좋은 카페',
        sources: ['105동'],
    },
    {
        name: '라이크어해빗',
        category: '카페',
        emoji: '🫖',
        location: '의왕시 내손동 일대',
        menus: ['커피', '디저트'],
        note: '상호와 위치는 지도에서 한 번 더 확인해 주세요',
        sources: ['105동'],
        needsLocationCheck: true,
    },
    {
        name: '비올렛',
        category: '카페',
        emoji: '🍰',
        location: '의왕시 내손동 669-3',
        menus: ['케이크', '디저트', '커피'],
        note: '케이크와 커피를 함께 즐기기 좋은 곳',
        sources: ['105동'],
    },
    {
        name: '비루야',
        category: '일식',
        emoji: '🍱',
        location: '의왕시 내손1동 622-3 · 백운초 인근',
        menus: ['돈카츠'],
        note: '바삭한 카츠가 당기는 날의 선택지',
        sources: ['102동'],
    },
    {
        name: '만두빚는집',
        category: '한식',
        emoji: '🥟',
        location: '백운초등학교 인근',
        menus: ['콩국수', '들깨수제비'],
        note: '제보에 적힌 위치 기준이라 방문 전 확인이 필요해요',
        sources: ['102동'],
        needsLocationCheck: true,
        searchQuery: '만두빚는집 백운초 의왕',
    },
    {
        name: '루리네',
        category: '양식',
        emoji: '🍕',
        location: '의왕시 내손로 82 · 신성프라자 3층',
        menus: ['화덕피자', '파스타', '리조또'],
        note: '103동 이웃이 화덕피자를 콕 집어 추천했어요',
        sources: ['102동', '103동'],
        isNew: true,
    },
    {
        name: '쌍둥이곱창',
        category: '고기',
        emoji: '🔥',
        location: '안양시 동안구 평촌동 일대',
        menus: ['곱창', '막창'],
        note: '두 번 제보된 이웃 추천 곱창집',
        sources: ['103동', '106동'],
        isNew: true,
        needsLocationCheck: true,
        searchQuery: '쌍둥이곱창 평촌동',
    },
    {
        name: '상원손짜장',
        category: '중식',
        emoji: '🥢',
        location: '의왕시 백운로 596 · 청계동',
        menus: ['손짜장', '짬뽕'],
        note: '수타 면 요리가 생각날 때',
        sources: ['103동'],
    },
    {
        name: '호계신림순대국 아들집',
        category: '한식',
        emoji: '🍲',
        location: '안양시 동안구 흥안대로 426-17',
        menus: ['순대국'],
        note: '든든하고 뜨끈한 한 끼 선택지',
        sources: ['103동'],
    },
    {
        name: '마포최대포',
        category: '고기',
        emoji: '🥓',
        location: '의왕시 내손동 653-3 · 벨포레',
        menus: ['돼지갈비', '삼겹살'],
        note: '가족 외식이나 고기 모임 후보',
        sources: ['103동'],
    },
    {
        name: '옛골가마솥뼈다귀',
        category: '한식',
        emoji: '🍖',
        location: '내손동·평촌 생활권',
        menus: ['뼈다귀감자탕', '해장국'],
        note: '106동 이웃이 새로 추천한 곳',
        sources: ['106동'],
        isNew: true,
        needsLocationCheck: true,
        searchQuery: '옛골가마솥뼈다귀 의왕 내손동',
    },
    {
        name: '부뚜막족발',
        category: '한식',
        emoji: '🍖',
        location: '의왕시 내손2동 일대',
        menus: ['족발', '보쌈'],
        note: '106동 이웃이 추천한 동네 족발집',
        sources: ['106동'],
        isNew: true,
        needsLocationCheck: true,
        searchQuery: '부뚜막족발 의왕 내손2동',
    },
    {
        name: '시골순대국',
        category: '한식',
        emoji: '🥣',
        location: '내손동·평촌 생활권',
        menus: ['순대국'],
        note: '106동 이웃의 든든한 한 끼 추천',
        sources: ['106동'],
        isNew: true,
        needsLocationCheck: true,
        searchQuery: '시골순대국 의왕 내손동',
    },
    {
        name: '그집보쌈',
        category: '한식',
        emoji: '🥬',
        location: '안양시 동안구 흥안대로 450-16',
        menus: ['마늘보쌈', '바지락칼국수'],
        note: '보쌈과 칼국수를 함께 먹기 좋은 이웃 추천',
        sources: ['106동'],
        isNew: true,
        searchQuery: '그집보쌈 칼국수 인덕원',
    },
];
