/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/view-counter/wrangler.jsonc --include-runtime=false workers/view-counter/src/worker-configuration.d.ts` (hash: 6a2d12f5b66f5e2ed01c6908c0232d2a)
interface __BaseEnv_Env {
	VIEW_COUNTER_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
