import fs from 'node:fs';
import path from 'node:path';

type CliOptions = {
    dryRun: boolean;
    mediaPath: string;
    model: string;
    notesPath: string | null;
    outPath: string | null;
    overwrite: boolean;
    postPath: string | null;
};

type RideFrame = {
    cadence?: number | null;
    distanceKm?: number;
    elapsedSec?: number;
    heading?: number | null;
    heartRate?: number | null;
    index: number;
    lat?: number;
    lng?: number;
    speedKmh?: number | null;
    src: string;
    time: string;
};

type RideManifest = {
    frames: RideFrame[];
    frameIntervalSec?: number;
    highlights?: (RideFrame | number)[];
    slug: string;
    trimmedGpxUrl: string;
    viewerStartTime: string;
};

type ResponsesApiResult = {
    output?: {
        content?: {
            text?: string;
            type?: string;
        }[];
        type?: string;
    }[];
    output_text?: string;
};

async function main() {
    const options = parseArgs(process.argv.slice(2));
    const manifest = JSON.parse(
        await fs.promises.readFile(options.mediaPath, 'utf8'),
    ) as RideManifest;
    validateManifest(manifest);

    const post = options.postPath
        ? await fs.promises.readFile(options.postPath, 'utf8')
        : '';
    const notes = options.notesPath
        ? await fs.promises.readFile(options.notesPath, 'utf8')
        : '';
    const outPath =
        options.outPath ?? path.join('drafts', `${manifest.slug}.assist.md`);
    const prompt = buildPrompt({ manifest, notes, post });

    if (!options.overwrite && fs.existsSync(outPath)) {
        throw new Error(`${outPath} already exists. Pass --overwrite to replace it.`);
    }

    await fs.promises.mkdir(path.dirname(outPath), { recursive: true });

    if (options.dryRun) {
        await fs.promises.writeFile(outPath, prompt, 'utf8');
        console.log(`Wrote dry-run prompt to ${outPath}`);
        return;
    }

    const content = await requestWritingAssist({
        model: options.model,
        prompt,
    });

    await fs.promises.writeFile(outPath, content, 'utf8');
    console.log(`Wrote ${outPath}`);
}

function parseArgs(args: string[]): CliOptions {
    if (args.includes('--help') || args.includes('-h')) {
        printHelp();
        process.exit(0);
    }

    const values = new Map<string, string>();
    const flags = new Set<string>();

    for (let i = 0; i < args.length; i += 1) {
        const item = args[i];
        if (!item.startsWith('--')) continue;

        const [key, inlineValue] = item.slice(2).split('=', 2);
        if (key === 'dry-run' || key === 'overwrite') {
            flags.add(key);
            continue;
        }

        const value = inlineValue ?? args[i + 1];
        if (!value || value.startsWith('--')) {
            throw new Error(`Missing value for --${key}`);
        }

        values.set(key, value);
        if (inlineValue === undefined) i += 1;
    }

    return {
        dryRun: flags.has('dry-run'),
        mediaPath: required(values, 'media'),
        model: values.get('model') ?? process.env.OPENAI_MODEL ?? 'gpt-5.4-mini',
        notesPath: values.get('notes') ?? null,
        outPath: values.get('out') ?? null,
        overwrite: flags.has('overwrite'),
        postPath: values.get('post') ?? null,
    };
}

function printHelp() {
    console.log(`Usage:
  npm run ride:assist -- \\
    --post rides/20260601-morning-ride.md \\
    --media public/rides/202606/20260601-morning-ride/media.json \\
    --notes raw/rides/20260601/notes.md

Options:
  --media       media.json path generated by ride:prepare
  --post        Ride markdown draft path
  --notes       Personal notes markdown path
  --out         Output assist markdown path, default drafts/<slug>.assist.md
  --model       OpenAI model, default OPENAI_MODEL or gpt-5.4-mini
  --dry-run     Write the prompt instead of calling the OpenAI API
  --overwrite   Replace an existing output file

Environment:
  OPENAI_API_KEY is required unless --dry-run is used.
`);
}

function required(values: Map<string, string>, key: string) {
    const value = values.get(key);
    if (!value) throw new Error(`Missing required option --${key}`);
    return value;
}

function validateManifest(manifest: RideManifest) {
    if (!manifest.slug) throw new Error('media.json is missing slug.');
    if (!manifest.viewerStartTime) {
        throw new Error('media.json is missing viewerStartTime.');
    }
    if (!Array.isArray(manifest.frames) || manifest.frames.length === 0) {
        throw new Error('media.json must contain at least one frame.');
    }
}

function buildPrompt(input: { manifest: RideManifest; notes: string; post: string }) {
    const routeSummary = summarizeRoute(input.manifest);
    const highlightedFrames = selectHighlightFrames(input.manifest);
    const sampledFrames = sampleFrames(input.manifest.frames, 12);

    return `# 역할

너는 개인 라이딩 블로그의 편집 보조자다. 완성 글을 대신 쓰지 말고, 글쓴이가
고를 수 있는 후보와 질문을 만든다.

# 반드시 지킬 원칙

- 없는 사건, 풍경, 대화, 감정, 날씨를 만들어내지 않는다.
- 사용자가 notes에 적은 감정과 기억만 확장한다.
- GPX/media 데이터로 확인되는 사실과 추측을 구분한다.
- 문체는 한국어 개인 블로그 톤으로 자연스럽게 제안한다.
- 결과는 마크다운으로 작성한다.

# 출력 형식

## 제목 후보

5개를 제안한다.

## Summary 후보

3개를 제안한다.

## 데이터로 확인되는 관찰

거리, 속도, 방향, 프레임 변화에서 확인 가능한 내용만 적는다.

## 메모에서 확장할 수 있는 감정

notes에 있는 내용만 바탕으로 적는다. notes가 비어 있으면 질문만 제안한다.

## 하이라이트 캡션 후보

각 하이라이트 이미지별로 2개씩 제안한다.

## 본문 작성 질문

글쓴이가 직접 채우면 좋은 질문 8개를 만든다.

## 다듬은 문단 후보

기존 초안이 있으면 2~3문단을 제안한다. 기존 초안이 없으면 짧은 도입 후보만
제안한다.

# 라이딩 요약

${JSON.stringify(routeSummary, null, 2)}

# 하이라이트 프레임

${JSON.stringify(highlightedFrames, null, 2)}

# 샘플 프레임

${JSON.stringify(sampledFrames, null, 2)}

# 사용자 메모

${input.notes || '(메모 없음)'}

# 기존 초안

${input.post || '(초안 없음)'}
`;
}

function summarizeRoute(manifest: RideManifest) {
    const first = manifest.frames[0];
    const last = manifest.frames[manifest.frames.length - 1];
    const speeds = manifest.frames
        .map((frame) => frame.speedKmh)
        .filter((value): value is number => Number.isFinite(value));

    return {
        frameCount: manifest.frames.length,
        frameIntervalSec: manifest.frameIntervalSec ?? null,
        maxDistanceKm: last.distanceKm ?? null,
        maxSpeedKmh: speeds.length ? round(Math.max(...speeds), 1) : null,
        meanSampledSpeedKmh: speeds.length
            ? round(speeds.reduce((sum, value) => sum + value, 0) / speeds.length, 1)
            : null,
        slug: manifest.slug,
        startFrame: compactFrame(first),
        startTime: manifest.viewerStartTime,
        trimmedGpxUrl: manifest.trimmedGpxUrl,
    };
}

function selectHighlightFrames(manifest: RideManifest) {
    const explicitHighlights = (manifest.highlights ?? [])
        .map((highlight) => {
            if (typeof highlight === 'number') {
                return manifest.frames.find((frame) => frame.index === highlight);
            }

            return manifest.frames.find((frame) => frame.index === highlight.index);
        })
        .filter((frame): frame is RideFrame => Boolean(frame));

    if (explicitHighlights.length) {
        return uniqueFrames(explicitHighlights).slice(0, 10).map(compactFrame);
    }

    return sampleFrames(manifest.frames, 5);
}

function sampleFrames(frames: RideFrame[], count: number) {
    if (frames.length <= count) return frames.map(compactFrame);

    const samples: RideFrame[] = [];
    for (let i = 0; i < count; i += 1) {
        const index = Math.round((i / Math.max(1, count - 1)) * (frames.length - 1));
        samples.push(frames[index]);
    }

    return uniqueFrames(samples).map(compactFrame);
}

function compactFrame(frame: RideFrame) {
    return {
        cadence: frame.cadence ?? null,
        distanceKm: frame.distanceKm ?? null,
        elapsedSec: frame.elapsedSec ?? null,
        heading: frame.heading ?? null,
        heartRate: frame.heartRate ?? null,
        index: frame.index,
        speedKmh: frame.speedKmh ?? null,
        src: frame.src,
        time: frame.time,
    };
}

function uniqueFrames(frames: RideFrame[]) {
    const seen = new Set<number>();
    return frames.filter((frame) => {
        if (seen.has(frame.index)) return false;
        seen.add(frame.index);
        return true;
    });
}

async function requestWritingAssist(input: { model: string; prompt: string }) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
        throw new Error(
            'OPENAI_API_KEY is required. Use --dry-run to inspect the prompt.',
        );
    }

    const response = await fetch('https://api.openai.com/v1/responses', {
        body: JSON.stringify({
            input: input.prompt,
            instructions:
                'You are a careful Korean writing assistant for a personal cycling blog.',
            max_output_tokens: 4000,
            model: input.model,
        }),
        headers: {
            Authorization: `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
        },
        method: 'POST',
    });

    if (!response.ok) {
        throw new Error(
            `OpenAI API failed: ${response.status} ${await response.text()}`,
        );
    }

    const data = (await response.json()) as ResponsesApiResult;
    const text = extractResponseText(data);
    if (!text) throw new Error('OpenAI API response did not include output text.');
    return text;
}

function extractResponseText(data: ResponsesApiResult) {
    if (data.output_text) return data.output_text;

    return (data.output ?? [])
        .flatMap((item) => item.content ?? [])
        .map((content) => content.text)
        .filter(Boolean)
        .join('\n');
}

function round(value: number, digits: number) {
    const factor = 10 ** digits;
    return Math.round(value * factor) / factor;
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
