import fs from 'node:fs';
import path from 'node:path';

type CliOptions = {
    mediaPath: string;
    mediaUrl: string | null;
    outPath: string | null;
    overwrite: boolean;
    summary: string | null;
    title: string | null;
};

type RideFrame = {
    cadence?: number | null;
    distanceKm?: number;
    elapsedSec?: number;
    heading?: number | null;
    heartRate?: number | null;
    index: number;
    lat?: number;
    lng?: number;
    speedKmh?: number | null;
    src: string;
    time: string;
};

type RideManifest = {
    frames: RideFrame[];
    highlights?: (RideFrame | number)[];
    slug: string;
    trimmedGpxUrl: string;
    viewerStartTime: string;
};

async function main() {
    const options = parseArgs(process.argv.slice(2));
    const manifest = JSON.parse(
        await fs.promises.readFile(options.mediaPath, 'utf8'),
    ) as RideManifest;

    validateManifest(manifest);

    const date = dateFromIso(manifest.viewerStartTime);
    const title = options.title ?? `${date} 라이딩 기록`;
    const summary =
        options.summary ?? 'GoPro 프레임과 GPX 경로로 다시 보는 라이딩 기록입니다.';
    const mediaManifestUrl =
        options.mediaUrl ?? publicUrlFromPath(options.mediaPath) ?? '';
    if (!mediaManifestUrl) {
        throw new Error(
            'Could not infer media manifest URL. Pass --media-url explicitly.',
        );
    }

    const highlights = selectHighlightFrames(manifest);
    const coverImage = highlights[0]?.src ?? manifest.frames[0].src;
    const outPath = options.outPath ?? path.join('rides', `${manifest.slug}.md`);

    if (!options.overwrite && fs.existsSync(outPath)) {
        throw new Error(`${outPath} already exists. Pass --overwrite to replace it.`);
    }

    await fs.promises.mkdir(path.dirname(outPath), { recursive: true });
    await fs.promises.writeFile(
        outPath,
        renderDraft({
            coverImage,
            date,
            highlights,
            manifest,
            mediaManifestUrl,
            summary,
            title,
        }),
        'utf8',
    );

    console.log(`Wrote ${outPath}`);
}

function parseArgs(args: string[]): CliOptions {
    if (args.includes('--help') || args.includes('-h')) {
        printHelp();
        process.exit(0);
    }

    const values = new Map<string, string>();
    const flags = new Set<string>();

    for (let i = 0; i < args.length; i += 1) {
        const item = args[i];
        if (!item.startsWith('--')) continue;

        const [key, inlineValue] = item.slice(2).split('=', 2);
        if (key === 'overwrite') {
            flags.add(key);
            continue;
        }

        const value = inlineValue ?? args[i + 1];
        if (!value || value.startsWith('--')) {
            throw new Error(`Missing value for --${key}`);
        }

        values.set(key, value);
        if (inlineValue === undefined) i += 1;
    }

    return {
        mediaPath: required(values, 'media'),
        mediaUrl: values.get('media-url') ?? null,
        outPath: values.get('out') ?? null,
        overwrite: flags.has('overwrite'),
        summary: values.get('summary') ?? null,
        title: values.get('title') ?? null,
    };
}

function printHelp() {
    console.log(`Usage:
  npm run ride:draft -- \\
    --media public/rides/202606/20260601-morning-ride/media.json \\
    --title "2026년 6월 1일 아침 라이딩" \\
    --summary "GoPro와 GPX로 다시 보는 아침 라이딩 기록"

Options:
  --media       media.json path generated by ride:prepare
  --media-url   Public manifest URL. Inferred from public/... when omitted
  --title       Ride post title
  --summary     Ride post summary
  --out         Output markdown path, default rides/<slug>.md
  --overwrite   Replace an existing markdown file
`);
}

function required(values: Map<string, string>, key: string) {
    const value = values.get(key);
    if (!value) throw new Error(`Missing required option --${key}`);
    return value;
}

function validateManifest(manifest: RideManifest) {
    if (!manifest.slug) throw new Error('media.json is missing slug.');
    if (!manifest.trimmedGpxUrl)
        throw new Error('media.json is missing trimmedGpxUrl.');
    if (!manifest.viewerStartTime) {
        throw new Error('media.json is missing viewerStartTime.');
    }
    if (!Array.isArray(manifest.frames) || manifest.frames.length === 0) {
        throw new Error('media.json must contain at least one frame.');
    }
}

function selectHighlightFrames(manifest: RideManifest) {
    const explicitHighlights = (manifest.highlights ?? [])
        .map((highlight) => {
            if (typeof highlight === 'number') {
                return manifest.frames.find((frame) => frame.index === highlight);
            }

            return manifest.frames.find((frame) => frame.index === highlight.index);
        })
        .filter((frame): frame is RideFrame => Boolean(frame));

    if (explicitHighlights.length) return uniqueFrames(explicitHighlights).slice(0, 8);

    const desiredIndexes = [
        0,
        Math.floor(manifest.frames.length * 0.25),
        Math.floor(manifest.frames.length * 0.5),
        Math.floor(manifest.frames.length * 0.75),
        manifest.frames.length - 1,
    ];

    return uniqueFrames(
        desiredIndexes.map((index) => manifest.frames[Math.max(0, index)]),
    ).slice(0, 5);
}

function uniqueFrames(frames: RideFrame[]) {
    const seen = new Set<number>();
    return frames.filter((frame) => {
        if (seen.has(frame.index)) return false;
        seen.add(frame.index);
        return true;
    });
}

function renderDraft(input: {
    coverImage: string;
    date: string;
    highlights: RideFrame[];
    manifest: RideManifest;
    mediaManifestUrl: string;
    summary: string;
    title: string;
}) {
    const bodyImages = input.highlights
        .map((frame, order) => renderHighlight(frame, order))
        .join('\n\n');

    return `---
title: ${yamlString(input.title)}
date: ${input.date}
summary: ${yamlString(input.summary)}
tags:
    - GPX
    - GoPro
    - 라이딩 기록
    - 자전거 코스
gpxUrl: ${input.manifest.trimmedGpxUrl}
mediaManifestUrl: ${input.mediaManifestUrl}
coverImage: ${input.coverImage}
roadviewUpdateIntervalMs: 10000
---

GoPro 프레임과 GPX 경로를 함께 보며 남기는 라이딩 기록 초안입니다. 그날의 길,
속도, 기억에 남는 장면을 여기에 채워 넣습니다.

${bodyImages}
`;
}

function renderHighlight(frame: RideFrame, order: number) {
    const captionParts = [
        `${order + 1}번째 하이라이트`,
        Number.isFinite(frame.distanceKm)
            ? `${Number(frame.distanceKm).toFixed(1)} km 지점`
            : null,
        frame.speedKmh !== null && frame.speedKmh !== undefined
            ? `${frame.speedKmh.toFixed(1)} km/h`
            : null,
        frame.heading !== null && frame.heading !== undefined
            ? `진행 방향 ${Math.round(frame.heading)}도`
            : null,
    ].filter(Boolean);

    return `<figure>
  <img src="${frame.src}" alt="${captionParts.join(' · ')}" loading="lazy" />
  <figcaption>${captionParts.join(' · ')}</figcaption>
</figure>`;
}

function publicUrlFromPath(filePath: string) {
    const normalized = filePath.split(path.sep).join('/');
    const publicIndex = normalized.indexOf('public/');
    if (publicIndex < 0) return null;
    return `/${normalized.slice(publicIndex + 'public/'.length)}`;
}

function dateFromIso(value: string) {
    const date = new Date(value);
    if (!Number.isFinite(date.getTime())) {
        throw new Error(`Invalid viewerStartTime: ${value}`);
    }

    return date.toISOString().slice(0, 10);
}

function yamlString(value: string) {
    return JSON.stringify(value);
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
