name: Build and deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 17.x

      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: install devDependencies
        run: npm install

      - name: Gatsby Cache Folder
        uses: actions/cache@v1
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: |
            ${{ runner.os }}-cache-gatsby

      - name: Gatsby Public Folder
        uses: actions/cache@v1
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby

      - name: build
        run: npm run build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          ANALYTICS_CREDENTIALS: ${{ env.ANALYTICS_CREDENTIALS }}
          ANALYTICS_PROPERTY_ID: ${{ env.ANALYTICS_PROPERTY_ID }}
          GATSBY_VWORLD_API: ${{ env.GATSBY_VWORLD_API }}
          GATSBY_KAKAO_API: ${{ env.GATSBY_KAKAO_API }}        

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public/
          cname: blog.yeppyshiba.com
